#define TRAIT_TYPE_NEGATIVE	-1
#define TRAIT_TYPE_NEUTRAL	0
#define TRAIT_TYPE_POSITIVE	1

#define TRAIT_VARCHANGE_LESS_BETTER		-1
#define TRAIT_VARCHANGE_ALWAYS_OVERRIDE	0
#define TRAIT_VARCHANGE_MORE_BETTER		1