//THIS FILE IS AUTOMATICALLY GENERATED BY BAPI_DMM_READER, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

/* This comment bypasses grep checks */ /var/__bapi_dmm_reader

/proc/__detect_bapi_dmm_reader()
	if (world.system_type == UNIX)
		if(fexists("./libbapi_dmm_reader.so"))
			// No need for LD_LIBRARY_PATH badness.
			return __bapi_dmm_reader = "./libbapi_dmm_reader.so"
		// It's not in the current directory, so try others
		return __bapi_dmm_reader = "libbapi_dmm_reader"
	else
		return __bapi_dmm_reader = "bapi_dmm_reader"

#define BAPI_DMM_READER (__bapi_dmm_reader || __detect_bapi_dmm_reader())

/proc/_bapidmm_test_connection()
	return call_ext(BAPI_DMM_READER, "byond:_bapidmm_test_connection_ffi")()

/proc/_bapidmm_parse_map_blocking(dmm_file, map_datum)
	return call_ext(BAPI_DMM_READER, "byond:_bapidmm_parse_map_blocking_ffi")(dmm_file, map_datum)

/proc/_bapidmm_load_map_buffered(parsed_map, x_offset, y_offset, z_offset, crop_map, no_changeturf, x_lower,
x_upper, y_lower, y_upper, z_lower, z_upper, place_on_top, new_z)
	return call_ext(BAPI_DMM_READER, "byond:_bapidmm_load_map_buffered_ffi")(parsed_map, x_offset, y_offset, z_offset, crop_map, no_changeturf, x_lower,
x_upper, y_lower, y_upper, z_lower, z_upper, place_on_top, new_z)

/proc/_bapidmm_work_commandbuffer(parsed_map, resume_key)
	return call_ext(BAPI_DMM_READER, "byond:_bapidmm_work_commandbuffer_ffi")(parsed_map, resume_key)

/proc/_bapidmm_clear_map_data()
	return call_ext(BAPI_DMM_READER, "byond:_bapidmm_clear_map_data_ffi")()

/proc/bapidmm_generate_automata(limit_x, limit_y, iterations, initial_wall_cell)
	return call_ext(BAPI_DMM_READER, "byond:bapidmm_generate_automata_ffi")(limit_x, limit_y, iterations, initial_wall_cell)

#undef BAPI_DMM_READER
