version: '3'

services:
  # Virgo DM server
  dreammaker:
    image: vorestation:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "2303:2303"
    depends_on:
      - db
    volumes:
      - ./config/:/vorestation/config
      - gamedata:/vorestation/data
  # MariaDB/MySQL database: game 
  # (if you don't really need this, feel free to remove this section.)
  db:
    image: mariadb
    restart: unless-stopped
    env_file:
      - ./config/docker/mysql.env
    volumes: 
        - ./SQL/tgstation_schema.sql:/docker-entrypoint-initdb.d/tgstation_schema.sql:ro
        - ./SQL/feedback_schema.sql:/docker-entrypoint-initdb.d/feedback_schema.sql:ro
        - database:/var/lib/mysql
  # Adminer, for managing the DB, commented out by default but uncomment if you need it I guess.
  #adminer:
  #  image: wodby/adminer
  #  depends_on:
  #    - db
  #  environment:
  #    ADMINER_DEFAULT_DB_DRIVER: mysql
  #    ADMINER_DEFAULT_DB_HOST: db
  #    ADMINER_DEFAULT_DB_NAME: tgstation
  #    ADMINER_DESIGN: nette
  #    ADMINER_PLUGINS: tables-filter tinymce
  #  ports:
  #    - 8080:9000

volumes:
  gamedata:
  database:
