/mob/living/silicon/ai/Initialize(mapload, is_decoy, datum/ai_laws/L, obj/item/mmi/B, safety = FALSE)
	. = ..()
	add_language(LANGUAGE_BIRDSONG,		1)
	add_language(LANGUAGE_SAGARU,		1)
	add_language(LANGUAGE_CANILUNZT,	1)
	add_language(LANGUAGE_ECUREUILIAN,	1)
	add_language(LANGUAGE_DAEMON,		1)
	add_language(LANGUAGE_ENOCHIAN,		1)
	add_language(LANGUAGE_DRUDAKAR,		1)
	add_language(LANGUAGE_TAVAN,		1)

/mob/AIize(move = TRUE)
	. = ..()
	add_language(LANGUAGE_BIRDSONG,		1)
	add_language(LANGUAGE_SAGARU,		1)
	add_language(LANGUAGE_CANILUNZT,	1)
	add_language(LANGUAGE_ECUREUILIAN,	1)
	add_language(LANGUAGE_DAEMON,		1)
	add_language(LANGUAGE_ENOCHIAN,		1)
	add_language(LANGUAGE_DRUDAKAR,		1)
	add_language(LANGUAGE_TAVAN,		1)
