export const WikiPages = [
  'Food Recipes',
  'Drink Recipes',
  'Ores',
  'Materials',
  'Particle Physics',
  'Botany',
  'Catalogs',
];

export const wikiAds = [
  'Inferior ears? Teshari enhancement surgeries might be for you!',
  'Phoron huffers anonymous group chat. Join Today!',
  'Hot and single Vox raiders near your system!',
  'Need company? Holographic NIF friends! FREE DOWNLOAD!',
  'LostSpagetti.sol your one stop SYNX DATING website!',
  'HONK.bonk clown-only social media. Sign up TODAY!',
  'FREE ORGANS! FREE ORGANS! FREE ORGANS! Terms apply.',
  'Smile.me.com.net.skrell.node.exe.js DOWNLOAD NOW!',
  'Bankrupt? We can help! Buy uranium coins today!',
  "CONGRATULATIONS, you're our " +
    Math.floor(Math.random() * 1000 + 1) * 1000 +
    'th visitor! DOWNLOAD!',
  'Your system is out of date, DOWNLOAD DRIVERS!',
  "Ms.Kitty can't hang in there long, click here to support FELINE INDEPENDENCE!",
  'Cortical borer therapy! Treats anxiety, stress, and impending sense of univeral collapse!',
  'Help I licked the supermatter! And other strange stories from Nanotrasen. FREE PDF!',
  'TIME IS COMING TO AN END, BUY GOLD NOW!',
  'Your own pet clown? It sounds too REAL to be TRUE! VIEW ARTICLE!',
  'Are you a BIGSHOT? Investment opportunities inside!',
  'Spacestation13.exe FREE DOWNLOAD NOW!',
  'Bored and alone? Date a wizard today! WIZZBIZZ.KAZAM!',
  'Hot skrell babes in your area!',
];

export const WikiAdColors = [
  'black',
  'white',
  'red',
  'orange',
  'yellow',
  'olive',
  'green',
  'teal',
  'blue',
  'violet',
  'purple',
  'pink',
  'brown',
  'grey',
  'light-grey',
  '',
];

export const WikiDonIcons = [
  'dollar-sign',
  'sack-dollar',
  'money-check-dollar',
  'file-invoice-dollar',
  'circle-dollar-to-slot',
  'hand-holding-dollar',
  'credit-card',
  'euro-sign',
  'wallet',
  'coins',
  'yen-sign',
  'won-sign',
  'turkish-lira-sign',
  'tenge-sign',
  'sterling-sign',
  'shekel-sign',
  'rupiah-sign',
  'rupee-sign',
  'ruble-sign',
  'peso-sign',
  'peseta-sign',
  'naira-sign',
  'mill-sign',
  'manat-sign',
  'litecoin-sign',
  'lira-sign',
  'lari-sign',
  'kip-sign',
  'indian-rupee-sign',
  'hryvnia-sign',
  'guarani-sign',
  'franc-sign',
  'florin-sign',
  'dong-sign',
  'cruzeiro-sign',
  'colon-sign',
  'cent-sign',
  'cedi-sign',
  'brazilian-real-sign',
  'bitcoin-sign',
  'bangladeshi-taka-sign',
  'baht-sign',
  'austral-sign',
];

export const zeroC = 273.15;

export const WikiDonationMessages = [
  'Become a bingler today!',
  'Enjoying our content? Your donation keeps us in business!',
  'We all would love an ad free experience... Make it possible!',
  'Better to us than the Vox!',
  'Opersating and upkeeping trustworthy information since 1990.',
  'Suport or information revolution. From bluespace right into your brain.',
];

export const wikiDonatedMessages = [
  'You are awesome!',
  'Your support is appreciated!',
  "We'll do our best to improve your experience!",
  'Thank you! Thank you! Thank you!',
];

// Did you know?
export const WikiTippOfTheDay = [
  "Bingle wasn't built in typescript, but instead the crystalized tears of our programmers?",
  'Sleep()ing is illegal!',
  'Not all spaw()ns are friendly!',
  'A space carp a day keeps the virus away.',
  'Who thought two apple trees would be a good idea?',
  'Chemistry used to work on a trust based system? Where recipes had each chemical written down on their own post-it note per reaction!',
  'A toss to a wall once made everyone sprawl.',
  'New... New... New... why is it everywhere?',
  'Do we?',
  'Investments in books are so past century. Invest in bingle today!',
  'We can see the future!',
  'The code that runs Bingle is byond most mortal comprehension!',
  'You could just go on, milk that synx for inaprovaline!',
  "Appendicitis is actually contagious, don't listen to medical's lies!",
  'Bingle is more trustworthy then books written 200 years ago!',
  'Did you know, you can hallucinate forever?',
  'The pain never ends!',
  'Did you know? Skrell are 40% more likely to donate their bodies for research?',
  'You can do it all yourself, go on fork the code again, I dare you!',
  'Ceilings are a myth made to sell you roofs!',
  "It's illegal to turn elevators into showers in Solgov space!",
  'Supermatter, everywhere supermatter!',
  'You can live forever!',
  'Baits might have a telepathic side effect.',
  'There have been [' +
    Math.floor(Math.random() * 1000) +
    '] runtimes recorded by Bingle today!',
  '9 out of 10 doctors agree the supermatter tastes like ranch dressing!',
  'Some oceans have infinite gravity!',
  "Solgov has never said why it's illegal to have both a singularity and supermatter engine on the same station!",
  'Lead has the highest radiation resistance of all materials? Perfect for engine walls!',
  'In some regions of space, magic is illegal. Go on, try it nerd, your funny words have no power here!',
  'Forget who you are and summon the old gods.',
  "Who's that initialize and why do they always call their parents?",
  "Did you know? New isn't new anymore! It's so past century!",
  'Your kitchen is a chemistry set too!',
  'With Bingle, no sin will remain hidden from sight!',
];
