GLOBAL_LIST_INIT(bitfields, list(
	"datum_flags" = list(
		"DF_VAR_EDITED" = DF_VAR_EDITED,
		"DF_ISPROCESSING" = DF_ISPROCESSING
	),
	"appearance_flags" = list(
		"KEEP_APART" 		= KEEP_APART,
		"KEEP_TOGETHER"		= KEEP_TOGETHER,
		"LONG_GLIDE"		= LONG_GLIDE,
		"NO_CLIENT_COLOR"	= NO_CLIENT_COLOR,
		"PIXEL_SCALE"		= PIXEL_SCALE,
		"PLANE_MASTER"		= PLANE_MASTER,
		"RESET_ALPHA"		= RESET_ALPHA,
		"RESET_COLOR"		= RESET_COLOR,
		"RESET_TRANSFORM"	= RESET_TRANSFORM,
		"TILE_BOUND"		= TILE_BOUND,
		"PASS_MOUSE"		= PASS_MOUSE,
		"TILE_MOVER"		= TILE_MOVER
	),
	"vis_flags" = list(
		"VIS_HIDE"					= VIS_HIDE,
		"VIS_INHERIT_DIR"			= VIS_INHERIT_DIR,
		"VIS_INHERIT_ICON"			= VIS_INHERIT_ICON,
		"VIS_INHERIT_ICON_STATE"	= VIS_INHERIT_ICON_STATE,
		"VIS_INHERIT_ID"			= VIS_INHERIT_ID,
		"VIS_INHERIT_LAYER"			= VIS_INHERIT_LAYER,
		"VIS_INHERIT_PLANE"			= VIS_INHERIT_PLANE,
		"VIS_UNDERLAY"				= VIS_UNDERLAY,
	),
	"sight" = list(
		"BLIND"			= BLIND,
		"SEE_BLACKNESS"	= SEE_BLACKNESS,
		"SEE_INFRA"		= SEE_INFRA,
		"SEE_MOBS"		= SEE_MOBS,
		"SEE_OBJS"		= SEE_OBJS,
		"SEE_PIXELS"	= SEE_PIXELS,
		"SEE_SELF"		= SEE_SELF,
		"SEE_THRU"		= SEE_THRU,
		"SEE_TURFS"		= SEE_TURFS,
	),
))
