import { Icon } from 'tgui-core/components';

const rank2icon = {
  // Command Site Manager
  'Site Manager': 'user-tie',
  Overseer: 'user-tie',
  'Facility Director': 'user-tie',
  'Chief Supervisor': 'user-tie',
  Captain: 'user-tie',
  'Colony Director': 'user-tie',
  // HOP
  'Head of Personnel': 'briefcase',
  'Crew Resources Officer': 'briefcase',
  'Deputy Director': 'briefcase',
  'Staff Manager': 'briefcase',
  'Facility Steward': 'briefcase',
  'First Mate': 'briefcase',
  'Performance Management Supervisor': 'briefcase',
  // Secretary
  'Command Secretary': 'address-card',
  'Command Liaison': 'address-card',
  'Command Assistant': 'address-card',
  'Command Intern': 'address-card',
  'Bridge Secretary': 'address-card',
  'Bridge Assistant': 'address-card',
  'Bridge Officer': 'address-card',
  // Security HOS
  'Head of Security': 'user-shield',
  'Security Commander': 'user-shield',
  'Chief of Security': 'user-shield',
  'Security Managery': 'user-shield',
  // Warden
  Warden: ['city', 'shield-halved'],
  'Brig Sentry': ['city', 'shield-halved'],
  'Armory Superintendent': ['city', 'shield-halved'],
  'Master-at-Arms': ['city', 'shield-halved'],
  // Detective
  Detective: 'magnifying-glass',
  Investigator: 'magnifying-glass',
  'Security Inspector': 'magnifying-glass',
  'Forensic Technician': 'magnifying-glass',
  // Security Officer
  'Security Officer': 'shield',
  'Patrol Officer': 'shield',
  'Security Guard': 'shield',
  'Security Deputy': 'shield',
  'Junior Officer': 'shield',
  'Security Contractor': 'shield',
  // Engineering CE
  'Chief Engineer': 'screwdriver-wrench',
  'Head Engineer': 'screwdriver-wrench',
  Foreman: 'screwdriver-wrench',
  'Maintenance Manager': 'screwdriver-wrench',
  // Atmospheric Technician
  'Atmospheric Technician': 'wind',
  'Atmospheric Engineer': 'wind',
  'Atmospheric Maintainer': 'wind',
  'Disposals Technician': 'wind',
  'Fuel Technician': 'wind',
  // Engineer
  Engineer: 'toolbox',
  'Maintenance Technician': 'wrench',
  'Engine Technician': 'toolbox',
  Electrician: 'screwdriver',
  'Construction Engineer': 'trowel-bricks',
  'Engineering Contractor': 'ruler',
  // Medical CMO
  'Chief Medical Officer': 'user-doctor',
  'Chief Physician': 'user-doctor',
  'Medical Director': 'user-doctor',
  'Healthcare Manager': 'user-doctor',
  // Chemist
  Chemist: 'mortar-pestle',
  Pharmacist: 'mortar-pestle',
  Pharmacologist: 'mortar-pestle',
  // Medical Doctor
  'Medical Doctor': 'suitcase-medical',
  Physician: 'suitcase-medical',
  'Medical Practitioner': 'suitcase-medical',
  Surgeon: 'syringe',
  'Emergency Physician': 'suitcase-medical',
  Nurse: 'user-nurse',
  Orderly: 'book-medical',
  Virologist: 'disease',
  'Medical Contractor': 'notes-medical',
  // Paramedic
  Paramedic: 'truck-medical',
  'Emergency Medical Technician': 'truck-medical',
  'Medical Responder': 'truck-medical',
  'Search and Rescue': 'truck-droplet',
  // Psychiatrist
  Psychiatrist: 'couch',
  Psychologist: 'couch',
  Psychoanalyst: 'couch',
  Psychotherapist: 'couch',
  // Genetecist
  Geneticist: 'dna',
  // Brig Physician
  'Brig Physician': ['kit-medical', 'shield-halved'],
  'Security Medic': ['kit-medical', 'shield-halved'],
  'Security Medic Care Unit': ['kit-medical', 'shield-halved'],
  'Penitentiary Medical Care Unit': ['kit-medical', 'shield-halved'],
  'Junior Brig Physician': ['kit-medical', 'shield-halved'],
  'Detention Health Officer': ['kit-medical', 'shield-halved'],
  // Science RD
  'Research Director': 'user-graduate',
  'Research Supervisor': 'user-graduate',
  'Research Manager': 'user-graduate',
  'Head of Development': 'user-graduate',
  'Head Scientist': 'user-graduate',
  // Roboticist
  Roboticist: 'robot',
  'Assembly Technician': 'screwdriver',
  'Biomechanical Engineer': ['wrench', 'heartbeat'],
  'Mechatronic Engineer': 'wrench',
  // Scientist
  Scientist: 'flask',
  Researcher: 'flask-vial',
  'Lab Assistant': 'flask',
  Xenoarchaeologist: 'bone',
  Xenopaleontologist: 'bone',
  Anomalist: 'atom',
  'Phoron Researcher': 'vials',
  'Gas Physicist': 'microscope',
  'Circuit Designer': 'car-battery',
  'Circuit Programmer': 'laptop-file',
  // Xenobiologist
  Xenobiologist: 'meteor',
  Xenozoologist: 'locust',
  Xenoanthropologist: 'bugs',
  // Xenobotanist
  Xenobotanist: ['biohazard', 'seedling'],
  Xenohydroponicist: ['biohazard', 'droplet'],
  Xenoflorist: ['biohazard', 'clover'],
  // Cargo QM
  Quartermaster: 'box-open',
  'Supply Chief': 'warehouse',
  'Logistics Manager': 'warehouse',
  'Cargo Supervisor': 'box-open',
  // Cargo Technician
  'Cargo Technician': 'box',
  'Cargo Loader': 'dolly',
  'Cargo Handler': 'boxes-stacked',
  'Supply Courier': 'people-carry-box',
  'Disposals Sorter': 'recycle',
  Mailman: 'envelopes-bulk',
  // Shaft Miner
  'Shaft Miner': 'helmet-safety',
  'Deep Space Miner': 'bore-hole',
  'Drill Technician': 'oil-well',
  Prospector: 'helmet-safety',
  Excavator: 'bore-hole',
  // Exploration Lead
  Pathfinder: 'binoculars',
  'Expedition Lead': 'binoculars',
  'Exploration Manager': 'binoculars',
  // Explorer
  Explorer: 'user-astronaut',
  Surveyor: 'user-astronaut',
  'Offsite Scout': 'user-astronaut',
  'Explorer Medic': ['user-astronaut', 'kit-medical'],
  'Explorer Technician': ['user-astronaut', 'screwdriver'],
  // Field Medic
  'Field Medic': ['suitcase-medical', 'user-astronaut'],
  'Expedition Medic': ['suitcase-medical', 'user-astronaut'],
  'Offsite Medic': ['suitcase-medical', 'user-astronaut'],
  // Pilot
  Pilot: 'shuttle-space',
  'Co-Pilot': 'shuttle-space',
  Navigator: 'shuttle-space',
  Helmsman: 'shuttle-space',
  // Barkeeper
  Bartender: 'glass-martini',
  Barkeeper: 'wine-glass',
  Barmaid: 'whiskey-glass',
  Barista: 'coffee',
  Mixologist: 'martini-glass-citrus',
  // Botanist
  Botanist: 'leaf',
  Hydroponicist: 'droplet',
  Gardener: 'leaf',
  Cultivator: 'spa',
  Farmer: 'plant-wilt',
  Florist: 'spa',
  Rancher: 'leaf',
  // Chef
  Chef: 'utensils',
  'Sous-chef': 'spoon',
  Cook: 'utensils',
  'Kitchen Worker': 'kitchen-set',
  // Chaplain
  Chaplain: 'place-of-worship',
  Counselor: 'cross',
  Preacher: 'cross',
  Missionary: 'cross',
  Priest: 'cross',
  Nun: 'church',
  Monk: 'place-of-worship',
  Guru: 'place-of-worship',
  // Entertainer
  Entertainer: 'smile-beam',
  Performer: 'smile-beam',
  Musician: 'guitar',
  Stagehand: 'smile-beam',
  Actor: 'face-laugh-wink',
  Dancer: 'face-smile',
  Singer: 'smusic',
  Magician: 'wand-magic-sparkles',
  Comedian: 'face-laugh-wink',
  Tragedian: 'face-sad-tear',
  Artist: 'smile-beam',
  'Game Master': 'dice',
  // Entrepreneur
  Entrepreneur: 'building',
  Lawyer: 'gavel',
  'Private Eye': 'user-secret',
  Bodyguard: 'person-military-pointing',
  'Personal Physician': 'star-of-life',
  Dentist: 'teeth',
  'Fitness Instructor': 'dumbbell',
  'Yoga Teacher': 'person-walking',
  Masseuse: 'bottle-droplet',
  Tradesperson: 'money-bill-trend-up',
  Streamer: 'desktop',
  Influencer: 'computer',
  'Paranormal Investigator': 'magnifying-glass-arrow-right',
  'Personal Secretary': 'pen-to-square',
  Stylist: 'hat-cowboy-side',
  Fisher: 'fish-fins',
  'Fortune Teller': 'golf-ball-tee',
  'Spirit Healer': 'ghost',
  // All of the interns
  Intern: 'school',
  'Apprentice Engineer': ['school', 'wrench'],
  'Research Intern': ['school', 'flask'],
  'Security Cadet': ['school', 'shield-halved'],
  'Jr. Cargo Tech': ['school', 'box'],
  'Jr. Explorer': ['school', 'user-astronaut'],
  Assistant: ['school', 'address-card'],
  Server: ['school', 'utensils'],
  'Technical Assistant': ['school', 'screwdriver'],
  'Medical Intern': ['school', 'user-nurse'],
  'Research Assistant"': ['school', 'flask'],
  Visitor: 'user',
  Resident: 'user',
  // IAA
  'Internal Affairs Agent': 'balance-scale',
  'Internal Affairs Liaison': 'balance-scale',
  'Internal Affairs Delegate': 'balance-scale',
  'Internal Affairs Investigator': 'balance-scale',
  // Janitor
  Janitor: 'broom',
  Custodian: 'broom',
  'Sanitation Technician': 'hand-sparkles',
  Maid: 'broom',
  'Garbage Collector': 'dumpster',
  // Librarian
  Librarian: 'book',
  Journalist: 'newspaper',
  Reporter: 'newspaper',
  Writer: 'book',
  Historian: 'chalkboard-teacher',
  Archivist: 'book',
  Professor: 'chalkboard-teacher',
  Academic: 'chalkboard-teacher',
  Philosopher: 'book',
  Curator: 'book',
  // Off duty
  'Off-duty Officer': 'tree-city',
  'Off-duty Engineer': 'tree-city',
  'Off-duty Medic': 'tree-city',
  'Off-duty Scientist': 'tree-city',
  'Off-duty Cargo': 'tree-city',
  'Off-duty Explorer': 'tree-city',
  'Off-duty Worker': 'tree-city',
  // AI / Robot
  AI: 'display',
  Cyborg: 'robot',
  Robot: 'robot',
  Drone: 'robot',
  // Clown / Mime
  Clown: 'bullhorn',
  Jester: 'bullhorn',
  Fool: 'bullhorn',
  Mime: 'face-grin-tears',
  Poseur: 'face-grin-tears',
  // Special roles
  'Emergency Responder': 'fighter-jet',
  // Talon
  'Talon Captain': ['location-arrow', 'user-tie'],
  'Talon Commander': ['location-arrow', 'user-tie'],
  'Talon Doctor': ['location-arrow', 'suitcase-medical'],
  'Talon Medic': ['location-arrow', 'suitcase-medical'],
  'Talon Engineer': ['location-arrow', 'wrench'],
  'Talon Technician': ['location-arrow', 'screwdriver'],
  'Talon Guard': ['location-arrow', 'shield'],
  'Talon Security': ['location-arrow', 'shield'],
  'Talon Marine': ['location-arrow', 'shield'],
  'Talon Pilot': ['location-arrow', 'shuttle-space'],
  'Talon Helmsman': ['location-arrow', 'shuttle-space'],
  'Talon Miner': ['location-arrow', 'helmet-safety'],
  'Talon Excavator': ['location-arrow', 'helmet-safety'],
  // Robot Modules
  Standard: 'robot',
  Service: 'glass-martini',
  Clerical: 'pen-to-square',
  Research: 'flask',
  Miner: 'helmet-safety',
  Crisis: 'kit-medical',
  Security: 'shield',
  Combat: 'gun',
  Engineering: 'wrench',
  Gravekeeper: 'square-xmark',
  Lost: 'location-crosshairs',
  Protector: 'building-shield',
  Mechanist: 'gears',
  'Combat Medic': 'x-ray',
};

const rank2color = {
  // Command Site Manager
  'Site Manager': 'blue',
  Overseer: 'blue',
  'Facility Director': 'blue',
  'Chief Supervisor': 'blue',
  Captain: 'blue',
  'Colony Director': 'blue',
  // HOP
  'Head of Personnel': 'blue',
  'Crew Resources Officer': 'blue',
  'Deputy Director': 'blue',
  'Staff Manager': 'blue',
  'Facility Steward': 'blue',
  'First Mate': 'blue',
  'Performance Management Supervisor': 'blue',
  // Secretary
  'Command Secretary': 'blue',
  'Command Liaison': 'blue',
  'Command Assistant': 'blue',
  'Command Intern': 'blue',
  'Bridge Secretary': 'blue',
  'Bridge Assistant': 'blue',
  'Bridge Officer': 'blue',
  // Security HOS
  'Head of Security': 'blue',
  'Security Commander': 'blue',
  'Chief of Security': 'blue',
  'Security Managery': 'blue',
  // Warden
  Warden: 'red',
  'Brig Sentry': 'red',
  'Armory Superintendent': 'red',
  'Master-at-Arms': 'red',
  // Detective
  Detective: 'red',
  Investigator: 'red',
  'Security Inspector': 'red',
  'Forensic Technician': 'red',
  // Security Officer
  'Security Officer': 'red',
  'Patrol Officer': 'red',
  'Security Guard': 'red',
  'Security Deputy': 'red',
  'Junior Officer': 'red',
  'Security Contractor': 'red',
  // Engineering CE
  'Chief Engineer': 'blue',
  'Head Engineer': 'blue',
  Foreman: 'blue',
  'Maintenance Manager': 'blue',
  // Atmospheric Technician
  'Atmospheric Technician': 'orange',
  'Atmospheric Engineer': 'orange',
  'Atmospheric Maintainer': 'orange',
  'Disposals Technician': 'orange',
  'Fuel Technician': 'orange',
  // Engineer
  Engineer: 'orange',
  'Maintenance Technician': 'orange',
  'Engine Technician': 'orange',
  Electrician: 'orange',
  'Construction Engineer': 'orange',
  'Engineering Contractor': 'orange',
  // Medical CMO
  'Chief Medical Officer': 'blue',
  'Chief Physician': 'blue',
  'Medical Director': 'blue',
  'Healthcare Manager': 'blue',
  // Chemist
  Chemist: 'teal',
  Pharmacist: 'teal',
  Pharmacologist: 'teal',
  // Medical Doctor
  'Medical Doctor': 'teal',
  Physician: 'teal',
  'Medical Practitioner': 'teal',
  Surgeon: 'teal',
  'Emergency Physician': 'teal',
  Nurse: 'teal',
  Orderly: 'teal',
  Virologist: 'teal',
  'Medical Contractor': 'teal',
  // Paramedic
  Paramedic: 'teal',
  'Emergency Medical Technician': 'teal',
  'Medical Responder': 'teal',
  'Search and Rescue': 'teal',
  // Psychiatrist
  Psychiatrist: 'teal',
  Psychologist: 'teal',
  Psychoanalyst: 'teal',
  Psychotherapist: 'teal',
  // Genetecist
  Geneticist: 'teal',
  // Brig Physician
  'Brig Physician': 'teal',
  'Security Medic': 'teal',
  'Security Medic Care Unit': 'teal',
  'Penitentiary Medical Care Unit': 'teal',
  'Junior Brig Physician': 'teal',
  'Detention Health Officer': 'teal',
  // Science RD
  'Research Director': 'blue',
  'Research Supervisor': 'blue',
  'Research Manager': 'blue',
  'Head of Development': 'blue',
  'Head Scientist': 'blue',
  // Roboticist
  Roboticist: 'purple',
  'Assembly Technician': 'purple',
  'Biomechanical Engineer': 'purple',
  'Mechatronic Engineer': 'purple',
  // Scientist
  Scientist: 'purple',
  Researcher: 'purple',
  'Lab Assistant': 'purple',
  Xenoarchaeologist: 'purple',
  Xenopaleontologist: 'purple',
  Anomalist: 'purple',
  'Phoron Researcher': 'purple',
  'Gas Physicist': 'purple',
  'Circuit Designer': 'purple',
  'Circuit Programmer': 'purple',
  // Xenobiologist
  Xenobiologist: 'purple',
  Xenozoologist: 'purple',
  Xenoanthropologist: 'purple',
  // Xenobotanist
  Xenobotanist: 'purple',
  Xenohydroponicist: 'purple',
  Xenoflorist: 'purple',
  // Cargo QM
  Quartermaster: 'brown',
  'Supply Chief': 'brown',
  'Logistics Manager': 'brown',
  'Cargo Supervisor': 'brown',
  // Cargo Technician
  'Cargo Technician': 'brown',
  'Cargo Loader': 'brown',
  'Cargo Handler': 'brown',
  'Supply Courier': 'brown',
  'Disposals Sorter': 'brown',
  Mailman: 'brown',
  // Shaft Miner
  'Shaft Miner': 'brown',
  'Deep Space Miner': 'brown',
  'Drill Technician': 'brown',
  Prospector: 'brown',
  Excavator: 'brown',
  // Exploration Lead
  Pathfinder: 'blue',
  'Expedition Lead': 'blue',
  'Exploration Manager': 'blue',
  // Explorer
  Explorer: 'grey',
  Surveyor: 'grey',
  'Offsite Scout': 'grey',
  'Explorer Medic': 'grey',
  'Explorer Technician': 'grey',
  // Field Medic
  'Field Medic': 'grey',
  'Expedition Medic': 'grey',
  'Offsite Medic': 'grey',
  // Pilot
  Pilot: 'grey',
  'Co-Pilot': 'grey',
  Navigator: 'grey',
  Helmsman: 'grey',
  // Barkeeper
  Bartender: 'green',
  Barkeeper: 'green',
  Barmaid: 'green',
  Barista: 'green',
  Mixologist: 'green',
  // Botanist
  Botanist: 'green',
  Hydroponicist: 'green',
  Gardener: 'green',
  Cultivator: 'green',
  Farmer: 'green',
  Florist: 'green',
  Rancher: 'green',
  // Chef
  Chef: 'green',
  'Sous-chef': 'green',
  Cook: 'green',
  'Kitchen Worker': 'green',
  // Chaplain
  Chaplain: 'green',
  Counselor: 'green',
  Preacher: 'green',
  Missionary: 'green',
  Priest: 'green',
  Nun: 'green',
  Monk: 'green',
  Guru: 'green',
  // Entertainer
  Entertainer: 'green',
  Performer: 'green',
  Musician: 'green',
  Stagehand: 'green',
  Actor: 'green',
  Dancer: 'green',
  Singer: 'green',
  Magician: 'green',
  Comedian: 'green',
  Tragedian: 'green',
  Artist: 'green',
  'Game Master': 'green',
  // Entrepreneur
  Entrepreneur: 'green',
  Lawyer: 'green',
  'Private Eye': 'green',
  Bodyguard: 'green',
  'Personal Physician': 'green',
  Dentist: 'green',
  'Fitness Instructor': 'green',
  'Yoga Teacher': 'green',
  Masseuse: 'green',
  Tradesperson: 'green',
  Streamer: 'green',
  Influencer: 'green',
  'Paranormal Investigator': 'green',
  'Personal Secretary': 'green',
  Stylist: 'green',
  Fisher: 'green',
  'Fortune Teller': 'green',
  'Spirit Healer': 'green',
  // All of the interns
  Intern: 'green',
  'Apprentice Engineer': 'green',
  'Research Intern': 'green',
  'Security Cadet': 'green',
  'Jr. Cargo Tech': 'green',
  'Jr. Explorer': 'green',
  Assistant: 'green',
  Server: 'green',
  'Technical Assistant': 'green',
  'Medical Intern': 'green',
  'Research Assistant"': 'green',
  Visitor: 'green',
  Resident: 'green',
  // IAA
  'Internal Affairs Agent': 'blue',
  'Internal Affairs Liaison': 'blue',
  'Internal Affairs Delegate': 'blue',
  'Internal Affairs Investigator': 'blue',
  // Janitor
  Janitor: 'green',
  Custodian: 'green',
  'Sanitation Technician': 'green',
  Maid: 'green',
  'Garbage Collector': 'green',
  // Librarian
  Librarian: 'green',
  Journalist: 'green',
  Reporter: 'green',
  Writer: 'green',
  Historian: 'green',
  Archivist: 'green',
  Professor: 'green',
  Academic: 'green',
  Philosopher: 'green',
  Curator: 'green',
  // Off duty
  'Off-duty Officer': 'white',
  'Off-duty Engineer': 'white',
  'Off-duty Medic': 'white',
  'Off-duty Scientist': 'white',
  'Off-duty Cargo': 'white',
  'Off-duty Explorer': 'white',
  'Off-duty Worker': 'white',
  // AI / Robot
  AI: 'darkgrey',
  Cyborg: 'darkgrey',
  Robot: 'darkgrey',
  Drone: 'darkgrey',
  // Clown / Mime
  Clown: 'green',
  Jester: 'green',
  Fool: 'green',
  Mime: 'green',
  Poseur: 'green',
  // Special roles
  'Emergency Responder': 'yellow',
  // Talon
  'Talon Captain': 'grey',
  'Talon Commander': 'grey',
  'Talon Doctor': 'grey',
  'Talon Medic': 'grey',
  'Talon Engineer': 'grey',
  'Talon Technician': 'grey',
  'Talon Guard': 'grey',
  'Talon Security': 'grey',
  'Talon Marine': 'grey',
  'Talon Pilot': 'grey',
  'Talon Helmsman': 'grey',
  'Talon Miner': 'grey',
  'Talon Excavator': 'grey',
  // Robot Modules
  Standard: 'grey',
  Service: 'green',
  Clerical: 'blue',
  Research: 'purple',
  Miner: 'brown',
  Crisis: 'teal',
  Security: 'red',
  Combat: 'yellow',
  Engineering: 'orange',
  Gravekeeper: 'dark-grey',
  Lost: 'grey',
  Protector: 'darkred',
  Mechanist: 'darkred',
  'Combat Medic': 'darkred',
};

type rank_icon = { rank: string; color: string };

export const RankIcon = (props: rank_icon) => {
  const { rank, color = 'label' } = props;

  let rankObj = rank2icon[rank];
  if (typeof rankObj === 'string') {
    return <Icon inline color={color} name={rankObj} size={2} />;
  } else if (Array.isArray(rankObj)) {
    return rankObj.map((icon) => (
      <Icon inline key={icon} color={color} name={icon} size={2} />
    ));
  } else {
    return <Icon inline color={color} name="user" size={2} />;
  }
};
