//For use with various spawners! Put your selections inside of a list!
GLOBAL_LIST_EMPTY(theme_animal)
GLOBAL_LIST_EMPTY(theme_monster)
GLOBAL_LIST_EMPTY(theme_alien)
GLOBAL_LIST_EMPTY(theme_cold)
GLOBAL_LIST_EMPTY(theme_hot)
GLOBAL_LIST_EMPTY(theme_aquatic)
GLOBAL_LIST_EMPTY(theme_dark)
GLOBAL_LIST_EMPTY(theme_forest)
GLOBAL_LIST_EMPTY(theme_humanoid)
