#define TRAIT_TYPE_NEGATIVE	-1
#define TRAIT_TYPE_NEUTRAL	0
#define TRAIT_TYPE_POSITIVE	1

#define TRAIT_VARCHANGE_LESS_BETTER		-1
#define TRAIT_VARCHANGE_ALWAYS_OVERRIDE	0
#define TRAIT_VARCHANGE_MORE_BETTER		1

#define TRAIT_PREF_TYPE_BOOLEAN 1
#define TRAIT_PREF_TYPE_COLOR 2
#define TRAIT_PREF_TYPE_STRING 3

#define TRAIT_NO_VAREDIT_TARGET 0
#define TRAIT_VAREDIT_TARGET_SPECIES 1
#define TRAIT_VAREDIT_TARGET_MOB 2
