/datum/vore_look/proc/get_preference_data(mob/owner)
	return list(
		"digestable" = owner.digestable,
		"devourable" = owner.devourable,
		"resizable" = owner.resizable,
		"feeding" = owner.feeding,
		"absorbable" = owner.absorbable,
		"digest_leave_remains" = owner.digest_leave_remains,
		"allowmobvore" = owner.allowmobvore,
		"permit_healbelly" = owner.permit_healbelly,
		"show_vore_fx" = owner.show_vore_fx,
		"can_be_drop_prey" = owner.can_be_drop_prey,
		"can_be_drop_pred" = owner.can_be_drop_pred,
		"latejoin_vore" = owner.latejoin_vore,
		"latejoin_prey" = owner.latejoin_prey,
		"no_spawnpred_warning" = owner.no_latejoin_vore_warning,
		"no_spawnprey_warning" = owner.no_latejoin_prey_warning,
		"no_spawnpred_warning_time" = owner.no_latejoin_vore_warning_time,
		"no_spawnprey_warning_time" = owner.no_latejoin_prey_warning_time,
		"no_spawnpred_warning_save" = owner.no_latejoin_vore_warning_persists,
		"no_spawnprey_warning_save" = owner.no_latejoin_prey_warning_persists,
		"allow_spontaneous_tf" = owner.allow_spontaneous_tf,
		"step_mechanics_active" = owner.step_mechanics_pref,
		"pickup_mechanics_active" = owner.pickup_pref,
		"strip_mechanics_active" = owner.strip_pref,
		"noisy" = owner.noisy,
		//liquid belly prefs
		"liq_rec" = owner.receive_reagents,
		"liq_giv" = owner.give_reagents,
		"liq_apply" = owner.apply_reagents,
		"autotransferable" = owner.autotransferable,
		"noisy_full" = owner.noisy_full, //Belching while full
		"selective_active" = owner.selective_preference, //Reveal active selective mode in prefs

		"allow_mind_transfer" = owner.allow_mind_transfer,
		"drop_vore" = owner.drop_vore,
		"slip_vore" = owner.slip_vore,
		"stumble_vore" = owner.stumble_vore,
		"throw_vore" = owner.throw_vore,
		"phase_vore" = owner.phase_vore,
		"food_vore" = owner.food_vore,
		"consume_liquid_belly" = owner.consume_liquid_belly,
		"digest_pain" = owner.digest_pain,
		"nutrition_message_visible" = owner.nutrition_message_visible,
		"nutrition_messages" = owner.nutrition_messages,
		"weight_message_visible" = owner.weight_message_visible,
		"weight_messages" = owner.weight_messages,
		"eating_privacy_global" = owner.eating_privacy_global,
		"allow_mimicry" = owner.allow_mimicry,
		// start, vore sprites
		"belly_rub_target" = owner.belly_rub_target,
		"vore_sprite_color" = owner.vore_sprite_color,
		"vore_sprite_multiply" = owner.vore_sprite_multiply,
		//Soulcatcher
		"soulcatcher_allow_capture" = owner.soulcatcher_pref_flags & SOULCATCHER_ALLOW_CAPTURE,
		"soulcatcher_allow_transfer" = owner.soulcatcher_pref_flags & SOULCATCHER_ALLOW_TRANSFER,
		"soulcatcher_allow_takeover" = owner.soulcatcher_pref_flags & SOULCATCHER_ALLOW_TAKEOVER,
		"soulcatcher_allow_deletion" = (global_flag_check(owner.soulcatcher_pref_flags, SOULCATCHER_ALLOW_DELETION) + global_flag_check(owner.soulcatcher_pref_flags, SOULCATCHER_ALLOW_DELETION_INSTANT))
	)
