#define MAX_NUMBER_MEMORY				10000
#define MIN_NUMBER_MEMORY				-10000
#define MAX_STRING_MEMORY_LENGTH		20
#define MAX_STRING_CONCATINATOR_LENGTH	250
#define MIN_PULSER_TICK					5 SECONDS
#define DEFAULT_PART_COOLDOWN			3 SECONDS