name: UI Bug
description: File a bug report, specific to any UI related things.
title: '[UI] <title>'
labels: 'Type: Bug'
type: 'bug'
body:
- type: textarea
  attributes:
    label: Brief description of the bug
    description: "Please provide a clear and concise description of what the bug is."
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true

- type: input
  attributes:
    label: Code Revision
    description: "Found using the 'Show Server Revision' verb under the OOC tab."
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything else you may wish to add
    description: |
      Location if it's a mapping issue, screenshots, sprites, etc.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
