// Gasses

#define GAS_CO2 "carbon_dioxide"
#define GAS_N2 "nitrogen"
#define GAS_N2O "nitrous_oxide"
#define GAS_O2 "oxygen"
#define GAS_PHORON "phoron"
#define GAS_VOLATILE_FUEL "volatile_fuel"

// Gas Reagents
#define REAGENT_CARBON_DIOXIDE "Nitrogen"
#define REAGENT_NITROGEN "Nitrogen"
#define REAGENT_ID_NITROGEN "nitrogen"
#define REAGENT_NITROUS_OXIDE "Nitrous Oxide"
#define REAGENT_OXYGEN "Oxygen"
#define REAGENT_ID_OXYGEN "oxygen"
#define REAGENT_VOLATILE_FUEL "Volatile Fuel"
#define REAGENT_HYDROGEN "Hydrogen"
#define REAGENT_ID_HYDROGEN "hydrogen"
#define REAGENT_FLUORINE "Fluorine"
#define REAGENT_ID_FLUORINE "fluorine"
#define REAGENT_CHLORINE "Chlorine"
#define REAGENT_ID_CHLORINE "chlorine"


// Fluid Reagents
#define REAGENT_ETHANOL "Ethanol"
#define REAGENT_ID_ETHANOL "ethanol"
#define REAGENT_SACID "Sulphuric acid"
#define REAGENT_ID_SACID "sacid"
#define REAGENT_BLOOD "Blood"
#define REAGENT_ID_BLOOD "blood"
#define REAGENT_SYNTHBLOOD "synthetic blood"
#define REAGENT_ID_SYNTHBLOOD "synthblood"
#define REAGENT_SYNTHBLOOD_DILUTE "synthetic plasma"
#define REAGENT_ID_SYNTHBLOOD_DILUTE "synthblood_dilute"
#define REAGENT_ANTIBODIES "Antibodies"
#define REAGENT_ID_ANTIBODIES "antibodies"
#define REAGENT_WATER "Water"
#define REAGENT_ID_WATER "water"
#define REAGENT_FUEL "Welding fuel"
#define REAGENT_ID_FUEL "fuel"


// Solid Reagents
#define REAGENT_IRON "Iron"
#define REAGENT_ID_IRON "iron"
#define REAGENT_LITHIUM "Lithium"
#define REAGENT_ID_LITHIUM "lithium"
#define REAGENT_ALUMINIUM "Aluminum"
#define REAGENT_ID_ALUMINIUM "aluminum"
#define REAGENT_CALCIUM "Calcium"
#define REAGENT_ID_CALCIUM "calcium"
#define REAGENT_CARBON "Carbon"
#define REAGENT_ID_CARBON "carbon"
#define REAGENT_COPPER "Copper"
#define REAGENT_ID_COPPER "copper"
#define REAGENT_MERCURY "Mercury"
#define REAGENT_ID_MERCURY "mercury"
#define REAGENT_PHOSPHORUS "Phosphorus"
#define REAGENT_ID_PHOSPHORUS "phosphorus"
#define REAGENT_POTASSIUM "Potassium"
#define REAGENT_ID_POTASSIUM "potassium"
#define REAGENT_RADIUM "Radium"
#define REAGENT_ID_RADIUM "radium"
#define REAGENT_SILICON "Silicon"
#define REAGENT_ID_SILICON "silicon"
#define REAGENT_SODIUM "Sodium"
#define REAGENT_ID_SODIUM "sodium"
#define REAGENT_SUGAR "Sugar"
#define REAGENT_ID_SUGAR "sugar"
#define REAGENT_SULFUR "Sulfur"
#define REAGENT_ID_SULFUR "sulfur"
#define REAGENT_TUNGSTEN "Tungsten"
#define REAGENT_ID_TUNGSTEN "tungsten"
#define REAGENT_NUTRIMENT "Nutriment"
#define REAGENT_ID_NUTRIMENT "nutriment"


// Xeno chem react
#define XENO_CHEM_NUTRI "nutr"
#define XENO_CHEM_MUT "mut"
#define XENO_CHEM_TOXIC "toxic"
#define XENO_CHEM_HEAL "heal"


// VR reagents
#define REAGENT_SIZEOXADONE "Sizeoxadone"
#define REAGENT_ID_SIZEOXADONE "sizeoxadone"
#define REAGENT_MACROCILLIN "Macrocillin"
#define REAGENT_ID_MACROCILLIN "macrocillin"
#define REAGENT_MICROCILLIN "Microcillin"
#define REAGENT_ID_MICROCILLIN "microcillin"
#define REAGENT_NORMALCILLIN "Normalcillin"
#define REAGENT_ID_NORMALCILLIN "normalcillin"
#define REAGENT_ICKYPAK "Ickypak"
#define REAGENT_ID_ICKYPAK "ickypak"
#define REAGENT_UNSORBITOL "Unsorbitol"
#define REAGENT_ID_UNSORBITOL "unsorbitol"
#define REAGENT_AMORPHOROVIR "Amorphorovir"
#define REAGENT_ID_AMORPHOROVIR "amorphorovir"
#define REAGENT_ANDROROVIR "Androrovir"
#define REAGENT_ID_ANDROROVIR "androrovir"
#define REAGENT_GYNOROVIR "Gynorovir"
#define REAGENT_ID_GYNOROVIR "gynorovir"
#define REAGENT_ANDROGYNOROVIR "Androgynorovir"
#define REAGENT_ID_ANDROGYNOROVIR "androgynorovir"
#define REAGENT_RAINBOWTOXIN "Rainbow Toxin"
#define REAGENT_ID_RAINBOWTOXIN "rainbowtoxin"
#define REAGENT_PARALYSISTOXIN "Tetrodotoxin"
#define REAGENT_ID_PARALYSISTOXIN "paralysistoxin"
#define REAGENT_PAINENZYME "Pain Enzyme"
#define REAGENT_ID_PAINENZYME "painenzyme"


// Drugs
#define REAGENT_DRUGS "generic drugs"
#define REAGENT_ID_DRUGS "drugs"
#define REAGENT_BLISS "Bliss"
#define REAGENT_ID_BLISS "bliss"
#define REAGENT_AMBROSIAEXTRACT "Ambrosia extract"
#define REAGENT_ID_AMBROSIAEXTRACT "ambrosia_extract"
#define REAGENT_PSILOCYBIN "Psilocybin"
#define REAGENT_ID_PSILOCYBIN "psilocybin"
#define REAGENT_TALUMQUEM "Talum-quem"
#define REAGENT_ID_TALUMQUEM "talum_quem"
#define REAGENT_NICOTINE "Nicotine"
#define REAGENT_ID_NICOTINE "nicotine"
#define REAGENT_METHYLPHENIDATE "Methylphenidate"
#define REAGENT_ID_METHYLPHENIDATE "methylphenidate"
#define REAGENT_CITALOPRAM "Citalopram"
#define REAGENT_ID_CITALOPRAM "citalopram"
#define REAGENT_PAROXETINE "Paroxetine"
#define REAGENT_ID_PAROXETINE "paroxetine"
#define REAGENT_QERRQUEM "Qerr-quem"
#define REAGENT_ID_QERRQUEM "qerr_quem"


// Modifiers
#define REAGENT_BERSERKMED "brute juice"
#define REAGENT_ID_BERSERKMED "berserkmed"
#define REAGENT_CRYOSLURRY "cryogenic slurry"
#define REAGENT_ID_CRYOSLURRY "cryoslurry"
#define REAGENT_VATSTABILIZER "clone growth inhibitor"
#define REAGENT_ID_VATSTABILIZER "vatstabilizer"


// Medicines
#define REAGENT_ADRANOL "Adranol"
#define REAGENT_ID_ADRANOL "adranol"
#define REAGENT_NUMBENZYME "Numbing Enzyme"
#define REAGENT_ID_NUMBENZYME "numbenzyme"
#define REAGENT_VERMICETOL "Vermicetol"
#define REAGENT_ID_VERMICETOL "vermicetol"
#define REAGENT_SLEEVINGCURE "Kitsuhanan Cure"
#define REAGENT_ID_SLEEVINGCURE "sleevingcure"
#define REAGENT_PRUSSIANBLUE "Prussian Blue"
#define REAGENT_ID_PRUSSIANBLUE "prussian_blue"
#define REAGENT_LIPOZILASE "Lipozilase"
#define REAGENT_ID_LIPOZILASE "lipozilase"
#define REAGENT_LIPOSTIPO "Lipostipo"
#define REAGENT_ID_LIPOSTIPO "lipostipo"
#define REAGENT_POLYMORPH "Transforitine"
#define REAGENT_ID_POLYMORPH "polymorph"
#define REAGENT_GLAMOUR "Glamour"
#define REAGENT_ID_GLAMOUR "glamour"
#define REAGENT_INAPROVALINE "Inaprovaline"
#define REAGENT_ID_INAPROVALINE "inaprovaline"
#define REAGENT_INAPROVALAZE "Inaprovalaze"
#define REAGENT_ID_INAPROVALAZE "inaprovalaze"
#define REAGENT_BICARIDINE "Bicaridine"
#define REAGENT_ID_BICARIDINE "bicaridine"
#define REAGENT_BICARIDAZE "Bicaridaze"
#define REAGENT_ID_BICARIDAZE "bicaridaze"
#define REAGENT_CALCIUMCARBONATE "calcium carbonate"
#define REAGENT_ID_CALCIUMCARBONATE "calciumcarbonate"
#define REAGENT_KELOTANE "Kelotane"
#define REAGENT_ID_KELOTANE "kelotane"
#define REAGENT_DERMALINE "Dermaline"
#define REAGENT_ID_DERMALINE "dermaline"
#define REAGENT_DERMALAZE "Dermalaze"
#define REAGENT_ID_DERMALAZE "dermalaze"
#define REAGENT_ANTITOXIN "Dylovene"
#define REAGENT_ID_ANTITOXIN "anti_toxin"
#define REAGENT_CARTHATOLINE "Carthatoline"
#define REAGENT_ID_CARTHATOLINE "carthatoline"
#define REAGENT_DEXALIN "Dexalin"
#define REAGENT_ID_DEXALIN "dexalin"
#define REAGENT_DEXALINP "Dexalin Plus"
#define REAGENT_ID_DEXALINP "dexalinp"
#define REAGENT_TRICORDRAZINE "Tricordrazine"
#define REAGENT_ID_TRICORDRAZINE "tricordrazine"
#define REAGENT_TRICORLIDAZE "Tricorlidaze"
#define REAGENT_ID_TRICORLIDAZE "tricorlidaze"
#define REAGENT_CRYOXADONE "Cryoxadone"
#define REAGENT_ID_CRYOXADONE "cryoxadone"
#define REAGENT_CLONEXADONE "Clonexadone"
#define REAGENT_ID_CLONEXADONE "clonexadone"
#define REAGENT_MORTIFERIN "Mortiferin"
#define REAGENT_ID_MORTIFERIN "mortiferin"
#define REAGENT_NECROXADONE "Necroxadone"
#define REAGENT_ID_NECROXADONE "necroxadone"
#define REAGENT_PARACETAMOL "Paracetamol"
#define REAGENT_ID_PARACETAMOL "paracetamol"
#define REAGENT_TRAMADOL "Tramadol"
#define REAGENT_ID_TRAMADOL "tramadol"
#define REAGENT_OXYCODONE "Oxycodone"
#define REAGENT_ID_OXYCODONE "oxycodone"
#define REAGENT_SYNAPTIZINE "Synaptizine"
#define REAGENT_ID_SYNAPTIZINE "synaptizine"
#define REAGENT_HYPERZINE "Hyperzine"
#define REAGENT_ID_HYPERZINE "hyperzine"
#define REAGENT_ALKYSINE "Alkysine"
#define REAGENT_ID_ALKYSINE "alkysine"
#define REAGENT_IMIDAZOLINE "Imidazoline"
#define REAGENT_ID_IMIDAZOLINE "imidazoline"
#define REAGENT_PERIDAXON "Peridaxon"
#define REAGENT_ID_PERIDAXON "peridaxon"
#define REAGENT_OSTEODAXON "Osteodaxon"
#define REAGENT_ID_OSTEODAXON "osteodaxon"
#define REAGENT_MYELAMINE "Myelamine"
#define REAGENT_ID_MYELAMINE "myelamine"
#define REAGENT_RESPIRODAXON "Respirodaxon"
#define REAGENT_ID_RESPIRODAXON "respirodaxon"
#define REAGENT_GASTIRODAXON "Gastirodaxon"
#define REAGENT_ID_GASTIRODAXON "gastirodaxon"
#define REAGENT_HEPANEPHRODAXON "Hepanephrodaxon"
#define REAGENT_ID_HEPANEPHRODAXON "hepanephrodaxon"
#define REAGENT_CORDRADAXON "Cordradaxon"
#define REAGENT_ID_CORDRADAXON "cordradaxon"
#define REAGENT_IMMUNOSUPRIZINE "Immunosuprizine"
#define REAGENT_ID_IMMUNOSUPRIZINE "immunosuprizine"
#define REAGENT_MALISHQUALEM "Malish-Qualem"
#define REAGENT_ID_MALISHQUALEM "malish-qualem"
#define REAGENT_RYETALYN "Ryetalyn"
#define REAGENT_ID_RYETALYN "ryetalyn"
#define REAGENT_ETHYLREDOXRAZINE "Ethylredoxrazine"
#define REAGENT_ID_ETHYLREDOXRAZINE "ethylredoxrazine"
#define REAGENT_HYRONALIN "Hyronalin"
#define REAGENT_ID_HYRONALIN "hyronalin"
#define REAGENT_ARITHRAZINE "Arithrazine"
#define REAGENT_ID_ARITHRAZINE "arithrazine"
#define REAGENT_SPACEACILLIN "Spaceacillin"
#define REAGENT_ID_SPACEACILLIN "spaceacillin"
#define REAGENT_COROPHIZINE "Corophizine"
#define REAGENT_ID_COROPHIZINE "corophizine"
#define REAGENT_SPACOMYCAZE "Spacomycaze"
#define REAGENT_ID_SPACOMYCAZE "spacomycaze"
#define REAGENT_STERILIZINE "Sterilizine"
#define REAGENT_ID_STERILIZINE "sterilizine"
#define REAGENT_LEPORAZINE "Leporazine"
#define REAGENT_ID_LEPORAZINE "leporazine"
#define REAGENT_REZADONE "Rezadone"
#define REAGENT_ID_REZADONE "rezadone"
#define REAGENT_HEALINGNANITES "Restorative Nanites"
#define REAGENT_ID_HEALINGNANITES "healing_nanites"
#define REAGENT_MENTHOL "Menthol"
#define REAGENT_ID_MENTHOL "menthol"
#define REAGENT_EARTHSBLOOD "Earthsblood"
#define REAGENT_ID_EARTHSBLOOD "earthsblood"


// Virology
#define REAGENT_VACCINE "Vaccine"
#define REAGENT_ID_VACCINE "vaccine"
#define REAGENT_MUTAGENVIRUSFOOD "Mutagenic agar"
#define REAGENT_ID_MUTAGENVIRUSFOOD "mutagenvirusfood"
#define REAGENT_SUGARVIRUSFOOD "Sucrose agar"
#define REAGENT_ID_SUGARVIRUSFOOD "sugarvirusfood"
#define REAGENT_ADRANOLVIRUSFOOD "Virus rations"
#define REAGENT_ID_ADRANOLVIRUSFOOD "adranolvirusfood"
#define REAGENT_PHORONVIRUSFOOD "Phoronic virus food"
#define REAGENT_ID_PHORONVIRUSFOOD "phoronvirusfood"
#define REAGENT_WEAKPHORONVIRUSFOOD "Weakened phoronic virus food"
#define REAGENT_ID_WEAKPHORONVIRUSFOOD "weakphoronvirusfood"
#define REAGENT_SIZEVIRUSFOOD "Sizeoxadone virus food"
#define REAGENT_ID_SIZEVIRUSFOOD "sizevirusfood"


// Misc reagents
#define REAGENT_ADVMUTATIONTOXIN "Advanced Mutation Toxin"
#define REAGENT_ID_ADVMUTATIONTOXIN "advmutationtoxin"
#define REAGENT_NIFREPAIRNANITES "Programmed Nanomachines"
#define REAGENT_ID_NIFREPAIRNANITES "nifrepairnanites"
#define REAGENT_FIREFOAM "Firefighting Foam"
#define REAGENT_ID_FIREFOAM "firefoam"
#define REAGENT_LIQUIDPROTEAN "Liquid protean"
#define REAGENT_ID_LIQUIDPROTEAN "liquid_protean"
#define REAGENT_SHOCKCHEM "200 V"
#define REAGENT_ID_SHOCKCHEM "shockchem"
#define REAGENT_CRAYONDUST "Crayon dust"
#define REAGENT_ID_CRAYONDUST "crayon_dust"
#define REAGENT_CRAYONDUSTRED "Red crayon dust"
#define REAGENT_ID_CRAYONDUSTRED "crayon_dust_red"
#define REAGENT_CRAYONDUSTORANGE "Orange crayon dust"
#define REAGENT_ID_CRAYONDUSTORANGE "crayon_dust_orange"
#define REAGENT_CRAYONDUSTYELLOW "Yellow crayon dust"
#define REAGENT_ID_CRAYONDUSTYELLOW "crayon_dust_yellow"
#define REAGENT_CRAYONDUSTGREEN "Green crayon dust"
#define REAGENT_ID_CRAYONDUSTGREEN "crayon_dust_green"
#define REAGENT_CRAYONDUSTBLUE "Blue crayon dust"
#define REAGENT_ID_CRAYONDUSTBLUE "crayon_dust_blue"
#define REAGENT_CRAYONDUSTPURPLE "Purple crayon dust"
#define REAGENT_ID_CRAYONDUSTPURPLE "crayon_dust_purple"
#define REAGENT_CRAYONDUSTGREY "Grey crayon dust"
#define REAGENT_ID_CRAYONDUSTGREY "crayon_dust_grey"
#define REAGENT_CRAYONDUSTBROWN "Brown crayon dust"
#define REAGENT_ID_CRAYONDUSTBROWN "crayon_dust_brown"
#define REAGENT_MARKERINK "Marker ink"
#define REAGENT_ID_MARKERINK "marker_ink"
#define REAGENT_MARKERINKBLACK "Black marker ink"
#define REAGENT_ID_MARKERINKBLACK "marker_ink_black"
#define REAGENT_MARKERINKRED "Red marker ink"
#define REAGENT_ID_MARKERINKRED "marker_ink_red"
#define REAGENT_MARKERINKORANGE "Orange marker ink"
#define REAGENT_ID_MARKERINKORANGE "marker_ink_orange"
#define REAGENT_MARKERINKYELLOW "Yellow marker ink"
#define REAGENT_ID_MARKERINKYELLOW "marker_ink_yellow"
#define REAGENT_MARKERINKGREEN "Green marker ink"
#define REAGENT_ID_MARKERINKGREEN "marker_ink_green"
#define REAGENT_MARKERINKBLUE "Blue marker ink"
#define REAGENT_ID_MARKERINKBLUE "marker_ink_blue"
#define REAGENT_MARKERINKPURPLE "Purple marker ink"
#define REAGENT_ID_MARKERINKPURPLE "marker_ink_purple"
#define REAGENT_MARKERINKGREY "Grey marker ink"
#define REAGENT_ID_MARKERINKGREY "marker_ink_grey"
#define REAGENT_MARKERINKBROWN "Brown marker ink"
#define REAGENT_ID_MARKERINKBROWN "marker_ink_brown"
#define REAGENT_PAINT "Paint"
#define REAGENT_ID_PAINT "paint"
#define REAGENT_GOLD "Gold"
#define REAGENT_ID_GOLD "gold"
#define REAGENT_SILVER "Silver"
#define REAGENT_ID_SILVER "silver"
#define REAGENT_PLATINUM "Platinum"
#define REAGENT_ID_PLATINUM "platinum"
#define REAGENT_URANIUM "Uranium"
#define REAGENT_ID_URANIUM "uranium"
#define REAGENT_DEUTERIUM "Deuterium"
#define REAGENT_ID_DEUTERIUM "deuterium"
#define REAGENT_TRITIUM "Tritium"
#define REAGENT_ID_TRITIUM "tritium"
#define REAGENT_LITHIUM6 "Lithium-6"
#define REAGENT_ID_LITHIUM6 "lithium6"
#define REAGENT_HELIUM3 "Helium-3"
#define REAGENT_ID_HELIUM3 "helium3"
#define REAGENT_BORON11 "Boron-11"
#define REAGENT_ID_BORON11 "boron11"
#define REAGENT_SUPERMATTER "Supermatter"
#define REAGENT_ID_SUPERMATTER "supermatter"
#define REAGENT_ADRENALINE "Adrenaline"
#define REAGENT_ID_ADRENALINE "adrenaline"
#define REAGENT_HOLYWATER "Holy Water"
#define REAGENT_ID_HOLYWATER "holywater"
#define REAGENT_AMMONIA "Ammonia"
#define REAGENT_ID_AMMONIA "ammonia"
#define REAGENT_DIETHYLAMINE "Diethylamine"
#define REAGENT_ID_DIETHYLAMINE "diethylamine"
#define REAGENT_FLUOROSURFACTANT "Fluorosurfactant"
#define REAGENT_ID_FLUOROSURFACTANT "fluorosurfactant"
#define REAGENT_FOAMINGAGENT "Foaming agent"
#define REAGENT_ID_FOAMINGAGENT "foaming_agent"
#define REAGENT_THERMITE "Thermite"
#define REAGENT_ID_THERMITE "thermite"
#define REAGENT_CLEANER "Space cleaner"
#define REAGENT_ID_CLEANER "cleaner"
#define REAGENT_LUBE "Space Lube"
#define REAGENT_ID_LUBE "lube"
#define REAGENT_SILICATE "Silicate"
#define REAGENT_ID_SILICATE "silicate"
#define REAGENT_GLYCEROL "Glycerol"
#define REAGENT_ID_GLYCEROL "glycerol"
#define REAGENT_NITROGLYCERIN "Nitroglycerin"
#define REAGENT_ID_NITROGLYCERIN "nitroglycerin"
#define REAGENT_COOLANT "Coolant"
#define REAGENT_ID_COOLANT "coolant"
#define REAGENT_GLUE "Ultra Glue"
#define REAGENT_ID_GLUE "glue"
#define REAGENT_WOODPULP "Wood Pulp"
#define REAGENT_ID_WOODPULP "woodpulp"
#define REAGENT_LUMINOL "Luminol"
#define REAGENT_ID_LUMINOL "luminol"
#define REAGENT_BIOMASS "Biomass"
#define REAGENT_ID_BIOMASS "biomass"
#define REAGENT_MINERALIZEDFLUID "Mineral-Rich Fluid"
#define REAGENT_ID_MINERALIZEDFLUID "mineralizedfluid"
#define REAGENT_DEFECTIVENANITES "Defective Nanites"
#define REAGENT_ID_DEFECTIVENANITES "defective_nanites"
#define REAGENT_FISHBAIT "Fish Bait"
#define REAGENT_ID_FISHBAIT "fishbait"
#define REAGENT_LIQUIDCARPET "Liquid Carpet"
#define REAGENT_ID_LIQUIDCARPET "liquidcarpet"
#define REAGENT_LIQUIDCARPETB "Liquid Black Carpet"
#define REAGENT_ID_LIQUIDCARPETB "liquidcarpetb"
#define REAGENT_LIQUIDCARPETBLU "Liquid Blue Carpet"
#define REAGENT_ID_LIQUIDCARPETBLU "liquidcarpetblu"
#define REAGENT_LIQUIDCARPETTUR "Liquid Turquoise Carpet"
#define REAGENT_ID_LIQUIDCARPETTUR "liquidcarpettur"
#define REAGENT_LIQUIDCARPETSBLU "Liquid Silver Blue Carpet"
#define REAGENT_ID_LIQUIDCARPETSBLU "liquidcarpetsblu"
#define REAGENT_LIQUIDCARPETC "Liquid Clown Carpet"
#define REAGENT_ID_LIQUIDCARPETC "liquidcarpetc"
#define REAGENT_LIQUIDCARPETP "Liquid Purple Carpet"
#define REAGENT_ID_LIQUIDCARPETP "liquidcarpetp"
#define REAGENT_LIQUIDCARPETO "Liquid Orange Carpet"
#define REAGENT_ID_LIQUIDCARPETO "liquidcarpeto"
#define REAGENT_ESSENTIALOIL "Essential Oils"
#define REAGENT_ID_ESSENTIALOIL "essential_oil"


// Admin chems
#define REAGENT_ADMINORDRAZINE "Adminordrazine"
#define REAGENT_ID_ADMINORDRAZINE "adminordrazine"


// Foods & Drinks
#define REAGENT_MEATCOLONY "A colony of meat cells"
#define REAGENT_ID_MEATCOLONY "meatcolony"
#define REAGENT_PLANTCOLONY "A colony of plant cells"
#define REAGENT_ID_PLANTCOLONY "plantcolony"
#define REAGENT_GRUBSHAKE "Grub shake"
#define REAGENT_ID_GRUBSHAKE "grubshake"
#define REAGENT_BURNOUT "Burnout"
#define REAGENT_ID_BURNOUT "burnout"
#define REAGENT_MONSTERTAMER "Monster Tamer"
#define REAGENT_ID_MONSTERTAMER "monstertamer"
#define REAGENT_PINKRUSSIAN "Pink Russian"
#define REAGENT_ID_PINKRUSSIAN "pinkrussian"
#define REAGENT_ORIGINALSIN "Original Sin"
#define REAGENT_ID_ORIGINALSIN "originalsin"
#define REAGENT_NEWYORKSOUR "New York Sour"
#define REAGENT_ID_NEWYORKSOUR "newyorksour"
#define REAGENT_WINDGARITA "WND-Garita"
#define REAGENT_ID_WINDGARITA "windgarita"
#define REAGENT_MUDSLIDE "Mudslide"
#define REAGENT_ID_MUDSLIDE "mudslide"
#define REAGENT_GALACTICPANIC "Galactic Panic Attack"
#define REAGENT_ID_GALACTICPANIC "galacticpanic"
#define REAGENT_BULLDOG "Space Bulldog"
#define REAGENT_ID_BULLDOG "bulldog"
#define REAGENT_SBAGLIATO "Negroni Sbagliato"
#define REAGENT_ID_SBAGLIATO "sbagliato"
#define REAGENT_ITALIANCRISIS "Italian Crisis"
#define REAGENT_ID_ITALIANCRISIS "italiancrisis"
#define REAGENT_SUGARRUSH "Sweet Rush"
#define REAGENT_ID_SUGARRUSH "sugarrush"
#define REAGENT_LOTUS "Lotus"
#define REAGENT_ID_LOTUS "lotus"
#define REAGENT_SHROOMJUICE "Dumb Shroom Juice"
#define REAGENT_ID_SHROOMJUICE "shroomjuice"
#define REAGENT_RUSSIANROULETTE "Russian Roulette"
#define REAGENT_ID_RUSSIANROULETTE "russianroulette"
#define REAGENT_LOVEMAKER "The Love Maker"
#define REAGENT_ID_LOVEMAKER "lovemaker"
#define REAGENT_HONEYSHOT "Honey Shot"
#define REAGENT_ID_HONEYSHOT "honeyshot"
#define REAGENT_APPLETINI "Appletini"
#define REAGENT_ID_APPLETINIT "appletini"
#define REAGENT_GLOWINGAPPLETINI "Glowing Appletini"
#define REAGENT_ID_GLOWINGAPPLETINI "glowingappletini"
#define REAGENT_SCSATW "Slow Comfortable Screw Against the Wall"
#define REAGENT_ID_SCSATW "scsatw"
#define REAGENT_CHOCCYMILK "Choccy Milk"
#define REAGENT_ID_CHOCCYMILK "choccymilk"
#define REAGENT_REDSPACEFLUSH "Redspace Flush"
#define REAGENT_ID_REDSPACEFLUSH "redspaceflush"
#define REAGENT_GRAVEYARD "Graveyard"
#define REAGENT_ID_GRAVEYARD "graveyard"
#define REAGENT_BIGBEER "Giant Beer"
#define REAGENT_ID_BIGBEER "bigbeer"
#define REAGENT_MANAGERSUMMONER "Manager Summoner"
#define REAGENT_ID_MANAGERSUMMONER "manager_summoner"
#define REAGENT_SWEETTEA "Sweet Tea"
#define REAGENT_ID_SWEETTEA "sweettea"
#define REAGENT_UNSWEETTEA "Unsweetened Tea"
#define REAGENT_ID_UNSWEETTEA "unsweettea"
#define REAGENT_HAIROFTHERAT "Hair of the Rat"
#define REAGENT_ID_HAIROFTHERAT "hairoftherat"
#define REAGENT_BEPIS "Bepis Cola"
#define REAGENT_ID_BEPIS "bepis"
#define REAGENT_BUZZFUZZ "Buzz Fuzz"
#define REAGENT_ID_BUZZFUZZ "buzz_fuzz"
#define REAGENT_SPRITEDCRANBERRY "Sprited Cranberry"
#define REAGENT_ID_SPRITEDCRANBERRY "sprited_cranberry"
#define REAGENT_SHAMBLERS "Shambler's Juice"
#define REAGENT_ID_SHAMBLERS "shamblers"
#define REAGENT_BRAINPROTEIN "grey matter"
#define REAGENT_ID_BRAINPROTEIN "brain_protein"
#define REAGENT_ID_REDBRAINPROTEIN "red_brain_protein"
#define REAGENT_PROTEINPOWDER "Protein Powder"
#define REAGENT_ID_PROTEINPOWDER "protein_powder"
#define REAGENT_PROTEINSHAKE "Protein Shake"
#define REAGENT_ID_PROTEINSHAKE "protein_shake"
#define REAGENT_VANILLAPROTEINPOWDER "Vanilla Protein Powder"
#define REAGENT_ID_VANILLAPROTEINPOWDER "vanilla_protein_powder"
#define REAGENT_VANILLAPROTEINSHAKE "Vanilla Protein Shake"
#define REAGENT_ID_VANILLAPROTEINSHAKER "vanilla_protein_shake"
#define REAGENT_BANANAPROTEINPOWDER "Banana Protein Powder"
#define REAGENT_ID_BANANAPROTEINPOWDER "banana_protein_powder"
#define REAGENT_BANANAPROTEINSHAKE "Banana Protein Shake"
#define REAGENT_ID_BANANAPROTEINSHAKE "banana_protein_shake"
#define REAGENT_CHOCOLATEPROTEINPOWDER "Chocolate Protein Powder"
#define REAGENT_ID_CHOCOLATEPROTEINPOWDER "chocolate_protein_powder"
#define REAGENT_CHOCOLATEPROTEINSHAKE "Chocolate Protein Shake"
#define REAGENT_ID_CHOCOLATEPROTEINSHAKE "chocolate_protein_shake"
#define REAGENT_STRAWBERRYPROTEINPOWDER "Strawberry Protein Powder"
#define REAGENT_ID_STRAWBERRYPROTEINPOWDER "strawberry_protein_powder"
#define REAGENT_STRAWBERRYPROTEINSHAKE "Strawberry Protein Shake"
#define REAGENT_ID_STRAWBERRYPROTEINSHAKE "strawberry_protein_shake"
#define REAGENT_SOUP "Soup"
#define REAGENT_ID_SOUP "generic_soup"
#define REAGENT_TOMATOSOUP "Tomato Soup"
#define REAGENT_ID_TOMATOSOUP "tomato_soup"
#define REAGENT_MUSHROOMSOUP "Cream of Mushroom Soup"
#define REAGENT_ID_MUSHROOMSOUP "mushroom_soup"
#define REAGENT_CHICKENSOUP "Cream of Chicken Soup"
#define REAGENT_ID_CHICKENSOUP "chicken_soup"
#define REAGENT_CHICKENNOODLESOUP "Chicken Noodle Soup"
#define REAGENT_ID_CHICKENNOODLESOUP "chicken_noodle_soup"
#define REAGENT_ONIONSOUP "Onion Soup"
#define REAGENT_ID_ONIONSOUP "onion_soup"
#define REAGENT_VEGETABLESOUP "Vegetable Soup"
#define REAGENT_ID_VEGETABLESOUP "vegetable_soup"
#define REAGENT_BEETSOUP "Beet Soup"
#define REAGENT_ID_BEETSOUP "beet_soup"
#define REAGENT_HOTNSOURSOUP "Hot & Sour Soup"
#define REAGENT_ID_HOTNSOURSOUP "hot_n_sour_soup"
#define REAGENT_NUKIE "Nukie"
#define REAGENT_ID_NUKIE "nukie"
#define REAGENT_NUKIEPEACH "Nukie Peach"
#define REAGENT_ID_NUKIEPEACH "nukie_peach"
#define REAGENT_NUKIEPEAR "Nukie Pear"
#define REAGENT_ID_NUKIEPEAR "nukie_pear"
#define REAGENT_NUKIECHERRY "Nukie Cherry"
#define REAGENT_ID_NUKIECHERRY "nukie_cherry"
#define REAGENT_NUKIEMELON "Nukie Melon"
#define REAGENT_ID_NUKIEMELON "nukie_melon"
#define REAGENT_NUKIEBANANA "Nukie Banana"
#define REAGENT_ID_NUKIEBANANA "nukie_banana"
#define REAGENT_NUKIEROSE "Nukie Rose"
#define REAGENT_ID_NUKIEROSE "nukie_rose"
#define REAGENT_NUKIELEMON "Nukie Lemon"
#define REAGENT_ID_NUKIELEMON "nukie_lemon"
#define REAGENT_NUKIEFRUIT "Nukie Fruit"
#define REAGENT_ID_NUKIEFRUIT "nukie_fruit"
#define REAGENT_NUKIESPECIAL "Nukie Limited Edition"
#define REAGENT_ID_NUKIESPECIAL "nukie_special"
#define REAGENT_NUKIEMEGA "Mega Nukie"
#define REAGENT_ID_NUKIEMEGA "nukie_mega"
#define REAGENT_NUKIEMEGASIGHT "Nukie Mega Plum"
#define REAGENT_ID_NUKIEMEGASIGHT "nukie_mega_sight"
#define REAGENT_NUKIEMEGAHEART "Nukie Mega Juice"
#define REAGENT_ID_NUKIEMEGAHEART "nukie_mega_heart"
#define REAGENT_NUKIEMEGASLEEP "Nukie Nega"
#define REAGENT_ID_NUKIEMEGASLEEP "nukie_mega_sleep"
#define REAGENT_NUKIEMEGASHOCK "Nukie Mega Shock"
#define REAGENT_ID_NUKIEMEGASHOCK "nukie_mega_shock"
#define REAGENT_NUKIEMEGAFAST "Nukie Mega Rapid"
#define REAGENT_ID_NUKIEMEGAFAST "nukie_mega_fast"
#define REAGENT_NUKIEMEGAHIGH "Nukie Mega Sky"
#define REAGENT_ID_NUKIEMEGAHIGH "nukie_mega_high"
#define REAGENT_NUKIEMEGASHRINK "Nukie Mega Shrink"
#define REAGENT_ID_NUKIEMEGASHRINK "nukie_mega_shrink"
#define REAGENT_NUKIEMEGAGROWTH "Nukie Mega Growth"
#define REAGENT_ID_NUKIEMEGAGROWTH "nukie_mega_growth"
#define REAGENT_COATING "coating"
#define REAGENT_ID_COATING "coating"
#define REAGENT_BATTER "batter mix"
#define REAGENT_ID_BATTER "batter"
#define REAGENT_BEERBATTER "beer batter mix"
#define REAGENT_ID_BEERBATTER "beerbatter"
#define REAGENT_TRIGLYCERIDE "triglyceride"
#define REAGENT_ID_TRIGLYCERIDE "triglyceride"
#define REAGENT_OIL "Oil"
#define REAGENT_ID_OIL "oil"
#define REAGENT_COOKINGOIL "Cooking Oil"
#define REAGENT_ID_COOKINGOIL "cookingoil"
#define REAGENT_CORNOIL "Corn Oil"
#define REAGENT_ID_CORNOIL "cornoil"
#define REAGENT_PEANUTOIL "Peanut Oil"
#define REAGENT_ID_PEANUTOIL "peanutoil"
#define REAGENT_GLUCOSE "Glucose"
#define REAGENT_ID_GLUCOSE "glucose"
#define REAGENT_PROTEIN "animal protein"
#define REAGENT_ID_PROTEIN "protein"
#define REAGENT_TOFU "tofu protein"
#define REAGENT_ID_TOFU "tofu"
#define REAGENT_SEAFOOD "seafood protein"
#define REAGENT_ID_SEAFOOD "seafood"
#define REAGENT_CHEESE "cheese"
#define REAGENT_ID_CHEESE "cheese"
#define REAGENT_EGG "egg yolk"
#define REAGENT_ID_EGG "egg"
#define REAGENT_MURK_PROTEIN "murkfin protein"
#define REAGENT_ID_MURK_PROTEIN "murk_protein"
#define REAGENT_BEANPROTEIN "beans"
#define REAGENT_ID_BEANPROTEIN "bean_protein"
#define REAGENT_HONEY "Honey"
#define REAGENT_ID_HONEY "honey"
#define REAGENT_MAYO "Mayonnaise"
#define REAGENT_ID_MAYO "mayo"
#define REAGENT_YEAST "Yeast"
#define REAGENT_ID_YEAST "yeast"
#define REAGENT_FLOUR "Flour"
#define REAGENT_ID_FLOUR "flour"
#define REAGENT_COFFEEPOWDER "Coffee Powder"
#define REAGENT_ID_COFFEEPOWDER "coffeepowder"
#define REAGENT_TEAPOWDER "Tea Powder"
#define REAGENT_ID_TEAPOWDER "teapowder"
#define REAGENT_DECAFTEAPOWDER "Decaf Tea Powder"
#define REAGENT_ID_DECAFTEAPOWDER "decafteapowder"
#define REAGENT_COCO "Coco Powder"
#define REAGENT_ID_COCO "coco"
#define REAGENT_CHOCOLATE "Chocolate"
#define REAGENT_ID_CHOCOLATE "chocolate"
#define REAGENT_INSTANTJUICE "Juice Powder"
#define REAGENT_ID_INSTANTJUICE "instantjuice"
#define REAGENT_INSTANTGRAPE "Grape Juice Powder"
#define REAGENT_ID_INSTANTGRAPE "instantgrape"
#define REAGENT_INSTANTORANGE "Orange Juice Powder"
#define REAGENT_ID_INSTANTORANGE "instantorange"
#define REAGENT_INSTANTWATERMELON "Watermelon Juice Powder"
#define REAGENT_ID_INSTANTWATERMELON "instantwatermelon"
#define REAGENT_INSTANTAPPLE "Apple Juice Powder"
#define REAGENT_ID_INSTANTAPPLE "instantapple"
#define REAGENT_SOYSAUCE "Soy Sauce"
#define REAGENT_ID_SOYSAUCE "soysauce"
#define REAGENT_VINEGAR "Vinegar"
#define REAGENT_ID_VINEGAR "vinegar"
#define REAGENT_KETCHUP "Ketchup"
#define REAGENT_ID_KETCHUP "ketchup"
#define REAGENT_MUSTARD "Mustard"
#define REAGENT_ID_MUSTARD "mustard"
#define REAGENT_BARBECUE "Barbeque Sauce"
#define REAGENT_ID_BARBECUE "barbecue"
#define REAGENT_RICE "Rice"
#define REAGENT_ID_RICE "rice"
#define REAGENT_CHERRYJELLY "Cherry Jelly"
#define REAGENT_ID_CHERRYJELLY "cherryjelly"
#define REAGENT_PEANUTBUTTER "Peanut Butter"
#define REAGENT_ID_PEANUTBUTTER "peanutbutter"
#define REAGENT_VANILLA "Vanilla Extract"
#define REAGENT_ID_VANILLA "vanilla"
#define REAGENT_DURIANPASTE "Durian Paste"
#define REAGENT_ID_DURIANPASTE "durianpaste"
#define REAGENT_VIRUSFOOD  "Virus Food"
#define REAGENT_ID_VIRUSFOOD "virusfood"
#define REAGENT_SPRINKLES "Sprinkles"
#define REAGENT_ID_SPRINKLES "sprinkles"
#define REAGENT_MINT "Mint"
#define REAGENT_ID_MINT "mint"
#define REAGENT_LIPOZINE "Lipozine"
#define REAGENT_ID_LIPOZINE "lipozine"
#define REAGENT_SODIUMCHLORIDE "Table Salt"
#define REAGENT_ID_SODIUMCHLORIDE "sodiumchloride"
#define REAGENT_BLACKPEPPER "Black Pepper"
#define REAGENT_ID_BLACKPEPPER "blackpepper"
#define REAGENT_ENZYME "Universal Enzyme"
#define REAGENT_ID_ENZYME "enzyme"
#define REAGENT_SPACESPICE "Wurmwoad"
#define REAGENT_ID_SPACESPICE "spacespice"
#define REAGENT_BROWNIEMIX "Brownie Mix"
#define REAGENT_ID_BROWNIEMIX "browniemix"
#define REAGENT_CAKEBATTER "Cake Batter"
#define REAGENT_ID_CAKEBATTER "cakebatter"
#define REAGENT_FROSTOIL "Frost Oil"
#define REAGENT_ID_FROSTOIL "frostoil"
#define REAGENT_CRYOTOXIN "Cryotoxin"
#define REAGENT_ID_CRYOTOXIN "cryotoxin"
#define REAGENT_CAPSAICIN "Capsaicin Oil"
#define REAGENT_ID_CAPSAICIN "capsaicin"
#define REAGENT_CONDENSEDCAPSAICIN "Condensed Capsaicin"
#define REAGENT_ID_CONDENSEDCAPSAICIN "condensedcapsaicin"

#define REAGENT_DRINK "Drink"
#define REAGENT_ID_DRINK "drink"

// Juices
#define REAGENT_BANANA "Banana Juice"
#define REAGENT_ID_BANANA "banana"
#define REAGENT_BERRYJUICE "Berry Juice"
#define REAGENT_ID_BERRYJUICE "berryjuice"
#define REAGENT_PINEAPPLEJUICE "Pineapple Juice"
#define REAGENT_ID_PINEAPPLEJUICE "pineapplejuice"
#define REAGENT_CARROTJUICE "Carrot juice"
#define REAGENT_ID_CARROTJUICE "carrotjuice"
#define REAGENT_LETTUCEJUICE "Lettuce Juice"
#define REAGENT_ID_LETTUCEJUICE "lettucejuice"
#define REAGENT_GRAPEJUICE "Grape Juice"
#define REAGENT_ID_GRAPEJUICE "grapejuice"
#define REAGENT_LEMONJUICE "Lemon Juice"
#define REAGENT_ID_LEMONJUICE "lemonjuice"
#define REAGENT_APPLEJUICE "Apple Juice"
#define REAGENT_ID_APPLEJUICE "applejuice"
#define REAGENT_LIMEJUICE "Lime Juice"
#define REAGENT_ID_LIMEJUICE "limejuice"
#define REAGENT_ORANGEJUICE "Orange juice"
#define REAGENT_ID_ORANGEJUICE "orangejuice"
#define REAGENT_POISONBERRYJUICE "Poison Berry Juice"
#define REAGENT_ID_POISONBERRYJUICE "poisonberryjuice"
#define REAGENT_POTATOJUICE "Potato Juice"
#define REAGENT_ID_POTATOJUICE "potatojuice"
#define REAGENT_TURNIPJUICE "Turnip Juice"
#define REAGENT_ID_TURNIPJUICE "turnipjuice"
#define REAGENT_TOMATOJUICE "Tomato Juice"
#define REAGENT_ID_TOMATOJUICE "tomatojuice"
#define REAGENT_WATERMELONJUICE "Watermelon Juice"
#define REAGENT_ID_WATERMELONJUICE "watermelonjuice"

// Drinks
#define REAGENT_MILK "Milk"
#define REAGENT_ID_MILK "milk"
#define REAGENT_CHOCOLATEMILK  "Chocolate Milk"
#define REAGENT_ID_CHOCOLATEMILK "chocolate_milk"
#define REAGENT_CREAM "Cream"
#define REAGENT_ID_CREAM "cream"
#define REAGENT_SOYMILK "Soy Milk"
#define REAGENT_ID_SOYMILK "soymilk"
#define REAGENT_MILKFOAM "Milk Foam"
#define REAGENT_ID_MILKFOAM "milk_foam"
#define REAGENT_TEA "Tea"
#define REAGENT_ID_TEA "tea"
#define REAGENT_TEADECAF "Decaf Tea"
#define REAGENT_ID_TEADECAF "teadecaf"
#define REAGENT_ICETEA "Iced Tea"
#define REAGENT_ID_ICETEA "icetea"
#define REAGENT_ICETEADECAF "Decaf Iced Tea"
#define REAGENT_ID_ICETEADECAF "iceteadecaf"
#define REAGENT_MINTTEA "Mint Tea"
#define REAGENT_ID_MINTTEA "minttea"
#define REAGENT_MINTTEADECAF "Decaf Mint Tea"
#define REAGENT_ID_MINTTEADECAF "mintteadecaf"
#define REAGENT_LEMONTEA "Lemon Tea"
#define REAGENT_ID_LEMONTEA "lemontea"
#define REAGENT_LEMONTEADECAF "Decaf Lemon Tea"
#define REAGENT_ID_LEMONTEADECAF "lemonteadecaf"
#define REAGENT_LIMETEA "Lime Tea"
#define REAGENT_ID_LIMETEA "limetea"
#define REAGENT_LIMETEADECAF "Decaf Lime Tea"
#define REAGENT_ID_LIMETEADECAF "limeteadecaf"
#define REAGENT_ORANGETEA "Orange Tea"
#define REAGENT_ID_ORANGETEA "orangetea"
#define REAGENT_ORANGETEADECAF "Decaf orange Tea"
#define REAGENT_ID_ORANGETEADECAF "orangeteadecaf"
#define REAGENT_BERRYTEA "Berry Tea"
#define REAGENT_ID_BERRYTEA "berrytea"
#define REAGENT_BERRYTEADECAF "Decaf Berry Tea"
#define REAGENT_ID_BERRYTEADECAF "berryteadecaf"
#define REAGENT_GREENTEA "Green Tea"
#define REAGENT_ID_GREENTEA "greentea"
#define REAGENT_CHAITEA "Chai Tea"
#define REAGENT_ID_CHAITEA "chaitea"
#define REAGENT_CHAITEADECAF "Decaf Chai Tea"
#define REAGENT_ID_CHAITEADECAF "chaiteadecaf"
#define REAGENT_COFFEE "Coffee"
#define REAGENT_ID_COFFEE "coffee"
#define REAGENT_ICECOFFEE "Iced Coffee"
#define REAGENT_ID_ICECOFFEE "icecoffee"
#define REAGENT_SOYLATTE "Soy Latte"
#define REAGENT_ID_SOYLATTE "soy_latte"
#define REAGENT_CAFELATTE "Cafe Latte"
#define REAGENT_ID_CAFELATTE "cafe_latte"
#define REAGENT_DECAF "Decaf Coffee"
#define REAGENT_ID_DECAF "decaf"
#define REAGENT_HOTCOCO "Hot Chocolate"
#define REAGENT_ID_HOTCOCO "hot_coco"
#define REAGENT_BLACKEYE "Black Eye Coffee"
#define REAGENT_ID_BLACKEYE "black_eye"
#define REAGENT_DRIPCOFFEE "Drip Coffee"
#define REAGENT_ID_DRIPCOFFEE "drip_coffee"
#define REAGENT_AMERICANO "Americano"
#define REAGENT_ID_AMERICANO "americano"
#define REAGENT_LONGBLACK "Long Black Coffee"
#define REAGENT_ID_LONGBLACK "long_black"
#define REAGENT_MACCHIATO "Macchiato"
#define REAGENT_ID_MACCHIATO "macchiato"
#define REAGENT_CORTADO "Cortado"
#define REAGENT_ID_CORTADO "cortado"
#define REAGENT_BREVE "Breve"
#define REAGENT_ID_BREVE "breve"
#define REAGENT_CAPPUCCINO "Cappuccino"
#define REAGENT_ID_CAPPUCCINO "cappuccino"
#define REAGENT_FLATWHITE "Flat White Coffee"
#define REAGENT_ID_FLATWHITE "flat_white"
#define REAGENT_MOCHA "Mocha"
#define REAGENT_ID_MOCHA "mocha"
#define REAGENT_VIENNA "Vienna"
#define REAGENT_ID_VIENNA "vienna"
#define REAGENT_SODAWATER "Soda Water"
#define REAGENT_ID_SODAWATER "sodawater"
#define REAGENT_TONIC "Tonic Water"
#define REAGENT_ID_TONIC "tonic"
#define REAGENT_LEMONADE "Lemonade"
#define REAGENT_ID_LEMONADE "lemonade"
#define REAGENT_MELONADE "Melonade"
#define REAGENT_ID_MELONADE "melonade"
#define REAGENT_APPLEADE "Appleade"
#define REAGENT_ID_APPLEADE "appleade"
#define REAGENT_PINEAPPLEADE "Pineappleade"
#define REAGENT_ID_PINEAPPLEADE "pineappleade"
#define REAGENT_KIRASPECIAL "Kira Special"
#define REAGENT_ID_KIRASPECIAL "kiraspecial"
#define REAGENT_BROWNSTAR "Brown Star"
#define REAGENT_ID_BROWNSTAR "brownstar"
#define REAGENT_BROWNSTARDECAF "Decaf Brown Star"
#define REAGENT_ID_BROWNSTARDECAF "brownstar_decaf"
#define REAGENT_MILKSHAKE "Milkshake"
#define REAGENT_ID_MILKSHAKE "milkshake"
#define REAGENT_CHOCOSHAKE "Chocolate Milkshake"
#define REAGENT_ID_CHOCOSHAKE "chocoshake"
#define REAGENT_BERRYSHAKE "Berry Milkshake"
#define REAGENT_ID_BERRYSHAKE "berryshake"
#define REAGENT_COFFEESHAKE "Coffee Milkshake"
#define REAGENT_ID_COFFEESHAKE "coffeeshake"
#define REAGENT_PEANUTMILKSHAKE "Peanut Milkshake"
#define REAGENT_ID_PEANUTMILKSHAKE "peanutmilkshake"
#define REAGENT_REWRITER "Rewriter"
#define REAGENT_ID_REWRITER "rewriter"
#define REAGENT_NUKACOLA "Nuka Cola"
#define REAGENT_ID_NUKACOLA "nuka_cola"
#define REAGENT_GRENADINE "Grenadine Syrup"
#define REAGENT_ID_GRENADINE "grenadine"
#define REAGENT_COLA "Space Cola"
#define REAGENT_ID_COLA "cola"
#define REAGENT_DECAFCOLA "Space Cola Free"
#define REAGENT_ID_DECAFCOLA "decafcola"
#define REAGENT_LEMONSODA "Lemon Soda"
#define REAGENT_ID_LEMONSODA "lemonsoda"
#define REAGENT_APPLESODA "Apple Soda"
#define REAGENT_ID_APPLESODA "applesoda"
#define REAGENT_STRAWSODA "Strawberry Soda"
#define REAGENT_ID_STRAWSODA "strawsoda"
#define REAGENT_ORANGESODA "Orange Soda"
#define REAGENT_ID_ORANGESODA "orangesoda"
#define REAGENT_GRAPESODA "Grape Soda"
#define REAGENT_ID_GRAPESODA "grapesoda"
#define REAGENT_SARSAPARILLA "Sarsaparilla"
#define REAGENT_ID_SARSAPARILLA "sarsaparilla"
#define REAGENT_PORKSODA "Bacon Soda"
#define REAGENT_ID_PORKSODA "porksoda"
#define REAGENT_SPACEMOUNTAINWIND "Mountain Wind"
#define REAGENT_ID_SPACEMOUNTAINWIND "spacemountainwind"
#define REAGENT_DRGIBB "Dr. Gibb"
#define REAGENT_ID_DRGIBB "dr_gibb"
#define REAGENT_SPACEUP "Space-Up"
#define REAGENT_ID_SPACEUP "space_up"
#define REAGENT_LEMONLIME "Lemon-Lime"
#define REAGENT_ID_LEMONLIME "lemon_lime"
#define REAGENT_GINGERALE "Ginger Ale"
#define REAGENT_ID_GINGERALE "gingerale"
#define REAGENT_ROOTBEER "R&D Root Beer"
#define REAGENT_ID_ROOTBEER "rootbeer"
#define REAGENT_DIETDRGIBB "Diet Dr. Gibb"
#define REAGENT_ID_DIETDRGIBB "diet_dr_gibb"
#define REAGENT_SHIRLEYTEMPLE "Shirley Temple"
#define REAGENT_ID_SHIRLEYTEMPLE "shirley_temple"
#define REAGENT_ROYROGERS "Roy Rogers"
#define REAGENT_ID_ROYROGERS "roy_rogers"
#define REAGENT_COLLINSMIX "Collins Mix"
#define REAGENT_ID_COLLINSMIX "collins_mix"
#define REAGENT_ARNOLDPALMER "Arnold Palmer"
#define REAGENT_ID_ARNOLDPALMER "arnold_palmer"
#define REAGENT_DOCTORSDELIGHT "The Doctor's Delight"
#define REAGENT_ID_DOCTORSDELIGHT "doctorsdelight"
#define REAGENT_DRYRAMEN "Dry Ramen"
#define REAGENT_ID_DRYRAMEN "dry_ramen"




#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_
#define REAGENT_
#define REAGENT_ID_







// Toxins
#define REAGENT_TOXIN "Toxin"
#define REAGENT_ID_TOXIN "toxin"
#define REAGENT_PACID "Polytrinic acid"
#define REAGENT_ID_PACID "pacid"
#define REAGEMT_PHORON "Phoron"
#define REAGENT_ID_PHORON "phoron"
#define REAGENT_SPIDERTOXIN "Spidertoxin"
#define REAGENT_ID_SPIDERTOXIN "spidertoxin"
#define REAGENT_LEAD "Lead"
#define REAGENT_ID_LEAD "lead"
#define REAGENT_PLASTICIDE "Plasticide"
#define REAGENT_ID_PLASTICIDE "plasticide"
#define REAGENT_AMATOXIN "Amatoxin"
#define REAGENT_ID_AMATOXIN "amatoxin"
#define REAGENT_CARPOTOXIN "Carpotoxin"
#define REAGENT_ID_CARPOTOXIN "carpotoxin"
#define REAGENT_NEUROTOXIC_PROTEIN "toxic protein"
#define REAGENT_ID_NEUROTOXIC_PROTEIN "neurotoxic_protein"
#define REAGENT_HYDROPHORON "Hydrophoron"
#define REAGENT_ID_HYDROPHORON "hydrophoron"
#define REAGENT_CYANIDE "Cyanide"
#define REAGENT_ID_CYANIDE "cyanide"
#define REAGENT_MOLD "Mold"
#define REAGENT_ID_MOLD "mold"
#define REAGENT_EXPIREDMEDICINE "Expired Medicine"
#define REAGENT_ID_EXPIREDMEDICINE "expired_medicine"
#define REAGENT_STIMM "Stimm"
#define REAGENT_ID_STIMM "stimm"
#define REAGENT_POTASSIUMCHLORIDE "Potassium Chloride"
#define REAGENT_ID_POTASSIUMCHLORIDE "potassium_chloride"
#define REAGENT_POTASSIUMCHLOROPHORIDE "Potassium Chlorophoride"
#define REAGENT_ID_POTASSIUMCHLOROPHORIDE "potassium_chlorophoride"
#define REAGENT_ZOMBIEPOWDER "Zombie Powder"
#define REAGENT_ID_ZOMBIEPOWDER "zombiepowder"
#define REAGENT_LICHPOWDER "Lich Powder"
#define REAGENT_ID_LICHPOWDER "lichpowder"
#define REAGENT_FERTILIZER "Fertilizer"
#define REAGENT_ID_FERTILIZER "fertilizer"
#define REAGENT_EZNUTRIENT "EZ Nutrient"
#define REAGENT_ID_EZNUTRIENT "eznutrient"
#define REAGENT_LEFT4ZED "Left-4-Zed"
#define REAGENT_ID_LEFT4ZED "left4zed"
#define REAGENT_ROBUSTHARVEST "Robust Harvest"
#define REAGENT_ID_ROBUSTHARVEST "robustharvest"
#define REAGENT_TANNIN "Tannin"
#define REAGENT_ID_TANNIN "tannin"
#define REAGENT_PLANTBGONE "Plant-B-Gone"
#define REAGENT_ID_PLANTBGONE "plantbgone"
#define REAGENT_SIFSAP "Sivian Sap"
#define REAGENT_ID_SIFSAP "sifsap"
#define REAGENT_STOMACID "Digestive acid"
#define REAGENT_ID_STOMACID "stomacid"
#define REAGENT_THERMITEV "Pyrotoxin"
#define REAGENT_ID_THERMITEV "thermite_v"
#define REAGENT_CONDENSEDCAPSAICINV "Irritant toxin"
#define REAGENT_ID_CONDENSEDCAPSAICINV "condensedcapsaicin_v"
#define REAGENT_LEXORIN "Lexorin"
#define REAGENT_ID_LEXORIN "lexorin"
#define REAGENT_MUTAGEN "Unstable mutagen"
#define REAGENT_ID_MUTAGEN "mutagen"
#define REAGENT_SLIMEJELLY "Slime Jelly"
#define REAGENT_ID_SLIMEJELLY "slimejelly"
#define REAGENT_STOXIN "Soporific"
#define REAGENT_ID_STOXIN "stoxin"
#define REAGENT_CHLORALHYDRATE "Chloral Hydrate"
#define REAGENT_ID_CHLORALHYDRATE "chloralhydrate"
#define REAGENT_BEER2 REAGENT_BEER
#define REAGENT_ID_BEER2 "beer2"
#define REAGENT_SEROTROTIUM "Serotrotium"
#define REAGENT_ID_SEROTROTIUM "serotrotium"
#define REAGENT_SEROTROTIUMV "Serotropic venom"
#define REAGENT_ID_SEROTROTIUMV "serotrotium_v"
#define REAGENT_CRYPTOBIOLIN "Cryptobiolin"
#define REAGENT_ID_CRYPTOBIOLIN "cryptobiolin"
#define REAGENT_IMPEDREZENE "Impedrezene"
#define REAGENT_ID_IMPEDREZENE "impedrezene"
#define REAGENT_MINDBREAKER "Mindbreaker Toxin"
#define REAGENT_ID_MINDBREAKER "mindbreaker"
#define REAGENT_MUTATIONTOXIN "Mutation Toxin"
#define REAGENT_ID_MUTATIONTOXIN "mutationtoxin"
#define REAGENT_DOCILITYTOXIN "Docility Toxin"
#define REAGENT_ID_DOCILITYTOXIN "docilitytoxin"
#define REAGENT_SHREDDINGNANITES REAGENT_HEALINGNANITES
#define REAGENT_ID_SHREDDINGNANITES "shredding_nanites"
#define REAGENT_IRRADIATEDNANITES REAGENT_HEALINGNANITES
#define REAGENT_ID_IRRADIATEDNANITES "irradiated_nanites"
#define REAGENT_NEUROPHAGENANITES REAGENT_HEALINGNANITES
#define REAGENT_ID_NEUROPHAGENANITES "neurophage_nanites"
#define REAGENT_SALMONELLA "Salmonella"
#define REAGENT_ID_SALMONELLA "salmonella"







Files left: food_drinks.dm,
includes: .dm
excludes: reagents.dm,ores.dm,materials.dm,mre.dm

	id = "lemon_juice_paint"
