#define CE_WITHDRAWL "withdrawl" // Withdrawl symptoms

var/list/addictives	    = list(REAGENT_ID_OXYCODONE,REAGENT_ID_NICOTINE,REAGENT_ID_HYPERZINE,REAGENT_ID_BLISS,REAGENT_ID_AMBROSIAEXTRACT,REAGENT_ID_TALUMQUEM,REAGENT_ID_METHYLPHENIDATE,REAGENT_ID_PARACETAMOL,REAGENT_ID_TRICORDRAZINE/* chomp: ,REAGENT_ID_QUADCORD*/,REAGENT_ID_ETHANOL,REAGENT_ID_COFFEE,REAGENT_ID_ASUSTENANCE)
var/list/fast_addictives= list(REAGENT_ID_OXYCODONE,REAGENT_ID_HYPERZINE,REAGENT_ID_BLISS) // needs to be in above list too
var/list/slow_addictives= list(REAGENT_ID_PARACETAMOL,REAGENT_ID_TRICORDRAZINE,REAGENT_ID_ASUSTENANCE,REAGENT_ID_ETHANOL,REAGENT_ID_NICOTINE,REAGENT_ID_COFFEE/* chomp: ,REAGENT_ID_QUADCORD*/) // needs to be in above list too
