#define SMITE_SHADEKIN_ATTACK		"Shadekin (Attack)"
#define SMITE_SHADEKIN_NOMF			"Shadekin (Devour)"
#define SMITE_REDSPACE_ABDUCT		"Redspace Abduction"
#define SMITE_AD_SPAM				"Ad Spam"
#define SMITE_AUTOSAVE				"10 Second Autosave"
#define SMITE_AUTOSAVE_WIDE			"10 Second Autosave (AoE)"
#define MODIFIY_ROBOT_MODULE_ADD	"Add a Module"
#define MODIFIY_ROBOT_MODULE_REMOVE	"Remove a Module"
#define MODIFIY_ROBOT_APPLY_UPGRADE	"Apply an Upgrade"
#define MODIFIY_ROBOT_SUPP_ADD		"Add Upgrade Support"
#define MODIFIY_ROBOT_SUPP_REMOVE	"Remove Upgrade Support"
#define MODIFIY_ROBOT_RADIOC_ADD	"Add a Radio Channel"
#define MODIFIY_ROBOT_RADIOC_REMOVE	"Remove a Radio Channel"
#define MODIFIY_ROBOT_COMP_ADD		"Replace a Component"
#define MODIFIY_ROBOT_COMP_REMOVE	"Remove a Component"
#define MODIFIY_ROBOT_SWAP_MODULE	"Swap a Robot Module"
#define MODIFIY_ROBOT_RESET_MODULE	"Fully Reset Robot Module"
#define MODIFIY_ROBOT_TOGGLE_ERT	"Toggle ERT Module Overwrite"
#define MODIFIY_ROBOT_TOGGLE_STATION_ACCESS "Toggle All Station Access Codes"
#define MODIFIY_ROBOT_TOGGLE_CENT_ACCESS	"Toggle Central Access Codes"
