#define SMITE_SHADEKIN_ATTACK		"Shadekin (Attack)"
#define SMITE_SHADEKIN_NOMF			"Shadekin (Devour)"
#define SMITE_REDSPACE_ABDUCT		"Redspace Abduction"
#define SMITE_AD_SPAM				"Ad Spam"
#define SMITE_AUTOSAVE				"10 Second Autosave"
#define SMITE_AUTOSAVE_WIDE			"10 Second Autosave (AoE)"
