
#define RIOTS 1
#define WILD_ANIMAL_ATTACK 2
#define INDUSTRIAL_ACCIDENT 3
#define BIOHAZARD_OUTBREAK 4
#define PIRATES 6
#define CORPORATE_ATTACK 7
#define ALIEN_RAIDERS 8
#define AI_LIBERATION 9
#define MOURNING 10
#define CULT_CELL_REVEALED 11
#define SECURITY_BREACH 12
#define ANIMAL_RIGHTS_RAID 13
#define FESTIVAL 14

#define SECURITY 1
#define FOOD 2
#define ANIMALS 3
#define MINERALS 4
#define EMERGENCY 5
#define GASEOUS 6
#define MAINTENANCE 7
#define ROBOTICS 8
#define BIOMEDICAL 9
