#define FACTION_BAR "bar"
#define FACTION_CLOWN "clown"
#define FACTION_NONE "None"
#define FACTION_STATION "Station"

#define FACTION_AEROSTAT_INSIDE "aerostat_inside"
#define FACTION_AEROSTAT_SURFACE "aerostat_surface"
#define FACTION_ASTEROID_BELT "asteroid_belt"
#define FACTION_BEACH_OUT "beach_out"
#define FACTION_BEACH_CAVE "beach_cave"
#define FACTION_DERELICT "derelict"
#define FACTION_OVERMAP "overmap"
#define FACTION_ROGUEMINES "roguemines"
#define FACTION_SPACE_ROCK "space_rock"
#define FACTION_SPOOKYLAND "spookyland"
#define FACTION_THEATRE "theatre"
#define FACTION_UNDERDARK "underdark"

#define FACTION_VIRGO2 "virgo2"
#define FACTION_VIRGO3B "virgo3b"

#define FACTION_ALTEVIAN "altevian"
#define FACTION_CULT "cult"
#define FACTION_GLAMOUR "glamour"
#define FACTION_PIRATE "pirate"
#define FACTION_SHADEKIN "shadekin"
#define FACTION_SPACE_GHOST "space ghost"
#define FACTION_SYNDICATE "syndicate"
#define FACTION_TECHNOMANCER "technomancer"
#define FACTION_VAMPIRE "vampire"

#define FACTION_CORRUPT "corrupt"
#define FACTION_HIVEBOT "hivebot"
#define FACTION_MALF_DRONE "malf_drone"
#define FACTION_VAGRANT "vagrant"
#define FACTION_WARDS "wards"

#define FACTION_ANIMAL "animal"
#define FACTION_BEE "bee"
#define FACTION_BLOB "blob"
#define FACTION_CARP "carp"
#define FACTION_CATGIRL "catgirl"
#define FACTION_CATSLUG "catslug"
#define FACTION_COOKIEGIRL "cookiegirl"
#define FACTION_CRABS "crabs"
#define FACTION_CREATURE "creature"
#define FACTION_DEATHCLAW "deathclaw"
#define FACTION_DEMON "demon"
#define FACTION_DEVIL "devil"
#define FACTION_DIYAAB "diyaab"
#define FACTION_DOG "dog"
#define FACTION_DRAGON "dragon"
#define FACTION_DUCK "duck"
#define FACTION_FAITHLESS "faithless"
#define FACTION_FENNEC "fennec"
#define FACTION_FOX "fox"
#define FACTION_GEESE "geese"
#define FACTION_GNAT "gnat"
#define FACTION_GOAT "goat"
#define FACTION_GOLEM "golem"
#define FACTION_GRAFADREKA "grafadreka"
#define FACTION_GRUBS "grubs"
#define FACTION_HORSE "horse"
#define FACTION_INSECTS "insects"
#define FACTION_JELLYFISH "jellyfish"
#define FACTION_KURUAK "kururak"
#define FACTION_LAMIA "lamia"
#define FACTION_LEECH "leech"
#define FACTION_MACROBACTERIA "macrobacteria"
#define FACTION_MEOWL "meowl"
#define FACTION_MIMIC "mimic"
#define FACTION_MOUSE "mouse"
#define FACTION_NANOMACHINES "nanomachines"
#define FACTION_NEUTRAL "neutral"
#define FACTION_OTIE "otie"
#define FACTION_PAKKUN "pakkun"
#define FACTION_PANTHER "panther"
#define FACTION_PEASANT "peasant"
#define FACTION_POLAR "polar"
#define FACTION_RABBIT "rabbit"
#define FACTION_RAPTOR "raptor"
#define FACTION_RAY "ray"
#define FACTION_REDPANDA "redpanda"
#define FACTION_RUSSIAN "russian"
#define FACTION_SAKIMM "sakimm"
#define FACTION_SAVIK "savik"
#define FACTION_SCARYBAT "scarybat"
#define FACTION_SCEL "scel"
#define FACTION_SCRUBBLE "scrubble"
#define FACTION_SEAGULL "seagull"
#define FACTION_SHANTAK "shantak"
#define FACTION_SHEEP "sheep"
#define FACTION_SIF "sif"
#define FACTION_SIFFET "siffet"
#define FACTION_SLIME "slime"
#define FACTION_SNAKE "snake"
#define FACTION_SONADILE "sonadile"
#define FACTION_SPACESHARK "spaceshark"
#define FACTION_SPACE_MOUSE "space mouse"
#define FACTION_SPACE_SKELETON "space skeleton"
#define FACTION_SPACE_TURTLE "space turtle"
#define FACTION_SPIDERS "spiders"
#define FACTION_STALKER "stalker"
#define FACTION_SUCCUBUS "succubus"
#define FACTION_SWARMER "swarmer"
#define FACTION_TEPPI "teppi"
#define FACTION_TUNNELCLOWN "tunnelclown"
#define FACTION_WILD_ANIMAL "wild animal"
#define FACTION_WOLFGIRL "wolfgirl"
#define FACTION_WOLFTAUR "wolftaur"
#define FACTION_WORM "worm"
#define FACTION_XENO "xeno"
#define FACTION_CORGI "corgi"

#define FACTION_PLANTS "plants"

#define FACTION_MATH "MATH"
