#define HALLUCINATION_THRESHOLD 20
#define XENOCHIFERAL_THRESHOLD 10

#define HUD_HALLUCINATION_NONE 0
#define HUD_HALLUCINATION_CRIT 1
#define HUD_HALLUCINATION_TOXIN 2
#define HUD_HALLUCINATION_OXY 3
#define HUD_HALLUCINATION_ONFIRE 4
