// Station Command jobs
#define JOB_SITE_MANAGER "Site Manager"
#define JOB_HEAD_OF_PERSONNEL "Head of Personnel"
#define JOB_COMMAND_SECRETARY "Command Secretary"
#define JOB_HEAD_OF_SECURITY "Head of Security"
#define JOB_CHIEF_ENGINEER "Chief Engineer"
#define JOB_RESEARCH_DIRECTOR "Research Director"
#define JOB_CHIEF_MEDICAL_OFFICER "Chief Medical Officer"
#define JOB_QUARTERMASTER "Quartermaster"
#define JOB_PATHFINDER "Away Team Leader" // was Pathfinder

// Station Security jobs
#define JOB_WARDEN "Warden"
#define JOB_DETECTIVE "Detective"
#define JOB_SECURITY_OFFICER "Security Officer"

// Station Engineering jobs
#define JOB_ATMOSPHERIC_TECHNICIAN "Atmospheric Technician"
#define JOB_ENGINEER "Engineer"

// Station Medical jobs
#define JOB_CHEMIST "Chemist"
#define JOB_MEDICAL_DOCTOR "Medical Doctor"
#define JOB_PARAMEDIC "Paramedic"
#define JOB_PSYCHIATRIST "Psychiatrist"
#define JOB_GENETICIST "Geneticist" //Disabled atm

// Station Science jobs
#define JOB_ROBOTICIST "Roboticist"
#define JOB_SCIENTIST "Scientist"
#define JOB_XENOBIOLOGIST "Xenobiologist"
#define JOB_XENOBOTANIST "Xenobotanist"

// Station Cargo jobs
#define JOB_SHAFT_MINER "Shaft Miner"
#define JOB_CARGO_TECHNICIAN "Cargo Technician"

// Section Explo jobs
#define JOB_EXPLORER "Away Team" // was Explorer
#define JOB_FIELD_MEDIC "Away Team Medic" // was Field Medic

// Station Civilian jobs
#define JOB_BARTENDER "Bartender"
#define JOB_BOTANIST "Botanist"
#define JOB_CHAPLAIN "Chaplain"
#define JOB_CHEF "Chef"
#define JOB_CLOWN "Clown"
#define JOB_ENTERTAINER "Entertainer"
#define JOB_ENTREPRENEUR "Entrepreneur"
#define JOB_INTERN "Intern"
#define JOB_INTERNAL_AFFAIRS_AGENT "Internal Affairs Agent"
#define JOB_JANITOR "Janitor"
#define JOB_LIBRARIAN "Librarian"
#define JOB_MIME "Mime"
#define JOB_PILOT "Pilot"

// Station Robot jobs
#define JOB_AI "AI"
#define JOB_CYBORG "Cyborg"

// Offduty jobs
#define JOB_OFFDUTY_OFFICER "Off-duty Officer"
#define JOB_OFFDUTY_ENGINEER "Off-duty Engineer"
#define JOB_OFFDUTY_MEDIC "Off-duty Medic"
#define JOB_OFFDUTY_SCIENTIST "Off-duty Scientist"
#define JOB_OFFDUTY_CARGO "Off-duty Cargo"
#define JOB_OFFDUTY_EXPLORER "Off-duty Explorer"
#define JOB_OFFDUTY_WORKER "Off-duty Worker"

// Talom jobs
#define JOB_TALON_CAPTAIN "Talon Captain"
#define JOB_TALON_DOCTOR "Talon Doctor"
#define JOB_TALON_ENGINEER "Talon Engineer"
#define JOB_TALON_GUARD "Talon Guard"
#define JOB_TALON_PILOT "Talon Pilot"
#define JOB_TALON_MINER "Talon Miner"

// Command alt titles
// Site Manager
#define JOB_ALT_OVERSEER "Overseer"
#define JOB_ALT_FACILITY_DIRECTOR "Facility Director"
#define JOB_ALT_CHIEF_SUPERVISOR "Chief Supervisor"
#define JOB_ALT_CAPTAIN "Captain"
// HOP
#define JOB_ALT_CREW_RESOURCE_OFFICER "Crew Resources Officer"
#define JOB_ALT_DEPUTY_MANAGER "Deputy Manager"
#define JOB_ALT_STAFF_MANAGER "Staff Manager"
#define JOB_ALT_FACILITY_STEWARD "Facility Steward"
#define JOB_ALT_FIRST_MATE "First Mate"
// Secretary
#define JOB_ALT_COMMAND_LIAISON "Command Liaison"
#define JOB_ALT_COMMAND_ASSISTANT "Command Assistant"
#define JOB_ALT_COMMAND_INTERN "Command Intern"
#define JOB_ALT_BRIDGE_SECRETARY "Bridge Secretary"
#define JOB_ALT_BRIDGE_ASSISTANT "Bridge Assistant"

// Security alt titles
#define JOB_ALT_FORENSIC_TECHNICIAN "Forensic Technician"
#define JOB_ALT_JUNIOR_OFFICER "Junior Officer"

// Medical alt titles
#define JOB_ALT_PHARMACIST "Pharmacist"
#define JOB_ALT_PHARMACOLOGIST "Pharmacologist"
#define JOB_ALT_VIROLOGIST "Virologist"

// Bartender alt titles
#define JOB_ALT_BARKEEPR "Barkeeper"
#define JOB_ALT_BARMAID "Barmaid"
#define JOB_ALT_BARISTA "Barista"
#define JOB_ALT_MIXOLOGIST "Mixologist"

// Botanist alt titles
#define JOB_ALT_GARDENER "Gardener"
#define JOB_ALT_HYDROPONICIST "Hydroponicist"
#define JOB_ALT_CULTIVATOR "Cultivator"
#define JOB_ALT_FARMER "Farmer"
#define JOB_ALT_FLORIST "Florist"
#define JOB_ALT_RANCHER "Rancher"

// Chef alt titles
#define JOB_ALT_SOUSCHEF "Sous-chef"
#define JOB_ALT_COOK "Cook"
#define JOB_ALT_KITCHEN_WORKER "Kitchen Worker"

// Service alt titles

// Chaplain alt titles
#define JOB_ALT_COUNSELOR "Counselor"


// Civilian alt titles
#define JOB_ALT_PASEUR "Poseur"
#define JOB_ALT_APPRENTICE_ENGINEER "Apprentice Engineer"
#define JOB_ALT_MEDICAL_INTERN "Medical Intern"
#define JOB_ALT_RESEARCH_INTERN "Research Intern"
#define JOB_ALT_SECURITY_CADET "Security Cadet"
#define JOB_ALT_JR_CARGO_TECH "Jr. Cargo Tech"
#define JOB_ALT_SERVER "Server"

#define JOB_ALT_ASSISTANT "Assistant"
#define JOB_ALT_RESIDENT "Resident"

// Station Robot alt titles
#define JOB_ALT_ROBOT "Robot"
#define JOB_ALT_DRONE "Drone"

// Talon alt jobs
#define JOB_ALT_TALON_COMMANDER "Talon Commander"
#define JOB_ALT_TALON_MEDIC "Talon Medic"
#define JOB_ALT_TALON_TECHNICIAN "Talon Technician"
#define JOB_ALT_TALON_SECURITY "Talon Security"
#define JOB_ALT_TALON_HELMSMAN "Talon Helmsman"
#define JOB_ALT_TALON_EXCAVATOR "Talon Excavator"

//Assistant/Visitor/Whatever
#define USELESS_JOB "Visitor"

// Mind jobs
#define JOB_SLIME "slime"
#define JOB_LARVA "Larva"
#define JOB_MONKEY "Monkey"
#define JOB_ANIMAL "Animal"
#define JOB_SIMPLE_MOB "Simple Mob"
#define JOB_CORGI "Corgi"
#define JOB_SHADE "Shade"
#define JOB_ARTIFICER "Artificer"
#define JOB_WRAITH "Wraith"
#define JOB_JUGGERNAUT "Juggernaut"
#define JOB_MODE = "MODE"
#define JOB_DISEMBODIED_VOICE "Disembodied Voice"
#define JOB_ALIEN "Alien"
#define JOB_GOLEM "Golem"
#define JOB_CORTICAL_BORER "Cortical Borer"

#define JOB_SYNTHETIC_BRAIN "Synthetic Brain"
#define JOB_ROBOTIC_INTELLIGENCE "Robotic Intelligence"
#define JOB_POSITRONIC_BRAIN "Positronic Brain"
#define JOB_CARBON_BASED "Carbon-based"
#define JOB_SILICON_BASED "Silicon-based"
#define JOB_PAI "pAI"
#define JOB_PROMETHEAN "Promethean"

#define JOB_LIVING "Living"
#define JOB_NEW_PLAYER "New player"
#define JOB_GHOST "Ghost"
#define JOB_GHOSTROLES "GhostRoles"
#define JOB_GRAFFITI "Graffiti"
#define JOB_RECORDS "Records"
#define JOB_DIONAEA "Dionaea"
#define JOB_CUSTOM_LOADOUT "Custom loadout"

// Speical Mind / Antag / Event jobs
#define JOB_CULTIST "Cultist"
#define JOB_MEME "Meme"
#define JOB_APPRENTICE "apprentice"
#define JOB_WIZARD "Wizard"
#define JOB_ANTAGHUD "AntagHUD"
#define JOB_CHANGELING "Changeling"
#define JOB_SYNDICATE "Syndicate"
#define JOB_XENOMORPH "Xenomorph"
#define JOB_BORER "Borer"
#define JOB_EMERGENCY_RESPONSE_TEAM "Emergency Response Team"

/* TODO

- "Supply Chief"
- "Logistics Manager"
- "Cargo Supervisor"
- "Cargo Loader"
- "Cargo Handler"
- "Supply Courier"
- "Disposals Sorter"
- "Deep Space Miner"
- "Drill Technician"
- "Prospector"
- "Excavator"
- "Custodian"
- "Sanitation Technician"
- "Maid"
- "Garbage Collector"
- "Journalist"
- "Reporter"
- "Writer"
- "Historian"
- "Archivist"
- "Professor"
- "Academic"
- "Philosopher"
- "Curator"
- "Internal Affairs Liaison"
- "Internal Affairs Delegate"
- "Internal Affairs Investigator"
- "Missionary"
- "Preacher"
- "Priest"
- "Nun"
- "Monk"
- "Guru"
- "Co-Pilot"
- "Navigator"
- "Helmsman"
- "Performer"
- "Musician"
- "Stagehand"
- "Actor"
- "Dancer"
- "Singer"
- "Magician"
- "Comedian"
- "Tragedian"
- "Artist"
- "Game Master"
- "Lawyer"
- "Private Eye"
- "Bodyguard"
- "Personal Physician"
- "Dentist"
- "Fitness Instructor"
- "Yoga Teacher"
- "Masseuse"
- "Tradesperson"
- "Streamer"
- "Influencer"
- "Paranormal Investigator"
- "Personal Secretary"
- "Stylist"
- "Fisher"
- "Fortune Teller"
- "Spirit Healer"
- "Barista"
- "Head Engineer"
- "Foreman"
- "Maintenance Manager"
- "Maintenance Technician"
- "Engine Technician"
- "Electrician"
- "Construction Engineer"
- "Engineering Contractor"
- "Atmospheric Engineer"
- "Atmospheric Maintainer"
- "Disposals Technician"
- "Fuel Technician"
- "Expedition Lead"
- "Exploration Manager"
- "Surveyor"
- "Offsite Scout"
- "Expedition Medic"
- "Offsite Medic"
- "Chief Physician"
- "Medical Director"
- "Healthcare Manager"
- "Physician"
- "Medical Practitioner"
- "Surgeon"
- "Emergency Physician"
- "Nurse"
- "Orderly"
- "Medical Contractor"
- "Psychologist"
- "Psychoanalyst"
- "Psychotherapist"
- "Emergency Medical Technician"
- "Medical Responder"
- "Search and Rescue"
- "Research Supervisor"
- "Research Manager"
- "Head of Development"
- "Head Scientist"
- "Researcher"
- "Lab Assistant"
- "Xenoarchaeologist"
- "Xenopaleontologist"
- "Anomalist"
- "Phoron Researcher"
- "Gas Physicist"
- "Circuit Designer"
- "Circuit Programmer"
- "Xenozoologist"
- "Xenoanthropologist"
- "Assembly Technician"
- "Biomechanical Engineer"
- "Mechatronic Engineer"
- "Xenohydroponicist"
- "Xenoflorist"
- "Brig Sentry"
- "Armory Superintendent"
- "Master-at-Arms"
- "Investigator"
- "Security Inspector"
- "Patrol Officer"
- "Security Guard"
- "Security Deputy"
- "Security Commander"
- "Chief of Security"
- "Jester"
- "Fool"
- "Technical Assistant"
- "Research Assistant"
- "Explorer Technician"
- "Explorer Medic"
*/
