#define MAINTVENDOR_GENERIC "Unsorted Listings"
#define MAINTVENDOR_SCENETOOLS "Funky Town Odds & Ends"
#define MAINTVENDOR_CONSTRUCTION "DIY Construction Supplies"
#define MAINTVENDOR_SWAG "BlingCo Product Distribution"
#define MAINTVENDOR_CLOTHING "2P1mpy & BapeCo. Clothing Conglomerate"
#define MAINTVENDOR_WEAPONS "W3APONS R US"
