//Handling and defining of phobias and fears
#define NYCTOPHOBIA 1
#define ARACHNOPHOBIA 2
#define HEMOPHOBIA 4
#define THALASSOPHOBIA 8
#define CLAUSTROPHOBIA_MINOR 16
#define CLAUSTROPHOBIA_MAJOR 32
#define ANATIDAEPHOBIA 64
#define AGRAVIAPHOBIA 128
