#define REFINERY_SINTERING_SMOKE "FLAG_SMOKE"
#define REFINERY_SINTERING_EXPLODE "FLAG_EXPLODE"
#define REFINERY_SINTERING_SPIDERS "FLAG_SPIDERS"

#define REAGENT_VAT_VOLUME 500
#define CARGOTANKER_VOLUME 3000
