#define SOULCATCHER_ALLOW_CAPTURE 			0x1
#define SOULCATCHER_ALLOW_TRANSFER 			0x2
#define SOULCATCHER_ALLOW_DELETION 			0x4
#define SOULCATCHER_ALLOW_DELETION_INSTANT 	0x8
#define SOULCATCHER_ALLOW_TAKEOVER 		0x10
