// Sorted by however I felt like it
// We have two other ways of doing this, so why not a third. This one atleast has more span options.
#define span_ooc(str) ("<span class='ooc'>" + str + "</span>")
#define span_looc(str) ("<span class='looc'>" + str + "</span>")

#define span_deadsay(str) ("<span class='deadsay'>" + str + "</span>")
#define span_radio(str) ("<span class='radio'>" + str + "</span>")
#define span_deptradio(str) ("<span class='deptradio'>" + str + "</span>")
#define span_newscaster(str) ("<span class='newscaster'>" + str + "</span>")

#define span_comradio(str) ("<span class='comradio'>" + str + "</span>")
#define span_syndradio(str) ("<span class='syndradio'>" + str + "</span>")
#define span_centradio(str) ("<span class='centradio'>" + str + "</span>"
#define span_airadio(str) ("<span class='airadio'>" + str + "</span>")
#define span_entradio(str) ("<span class='entradio'>" + str + "</span>")

#define span_secradio(str) ("<span class='secradio'>" + str + "</span>")
#define span_engradio(str) ("<span class='engradio'>" + str + "</span>")
#define span_medradio(str) ("<span class='medradio'>" + str + "</span>")
#define span_sciradio(str) ("<span class='sciradio'>" + str + "</span>")
#define span_supradio(str) ("<span class='supradio'>" + str + "</span>"
#define span_srvradio(str) ("<span class='srvradio'>" + str + "</span>")
#define span_expradio(str) ("<span class='expradio'>" + str + "</span>")

#define span_name(str) ("<span class='name'>" + str + "</span>")
#define span_say(str) ("<span class='say'>" + str + "</span>")
#define span_alert(str) ("<span class='alert'>" + str + "</span>")
#define span_ghostalert(str) ("<span class='ghostalert'>" + str + "</span>")


#define span_emote(str) ("<span class='emote'>" + str + "</span>")
#define span_emote_subtle(str) ("<span class='emotesubtle'>" + str + "</span>")

#define span_attack(str) ("<span class='attack'>" + str + "</span>")
#define span_moderate(str) ("<span class='moderate'>" + str + "</span>")
#define span_disarm(str) ("<span class='disarm'>" + str + "</span>")
#define span_passive(str) ("<span class='passive'>" + str + "</span>")

#define span_critical(str) ("<span class='critical'>" + str + "</span>")
#define span_danger(str) ("<span class='danger'>" + str + "</span>")
#define span_warning(str) ("<span class='warning'>" + str + "</span>")
#define span_rose(str) ("<span class='rose'>" + str + "</span>")
#define span_info(str) ("<span class='info'>" + str + "</span>")
#define span_notice(str) ("<span class='notice'>" + str + "</span>")
#define span_alium(str) ("<span class='alium'>" + str + "</span>")
#define span_cult(str) ("<span class='cult'>" + str + "</span>")

#define span_reflex_shoot(str) ("<span class='reflex_shoot'>" + str + "</span>")

/* Languages */

#define span_alien(str) ("<span class='alien'>" + str + "</span>")
#define span_tajaran(str) ("<span class='tajaran'>" + str + "</span>")
#define span_tajaran_signlang(str) ("<span class='tajaran_signlang'>" + str + "</span>")
#define span_akhani(str) ("<span class='akhani'>" + str + "</span>")
#define span_skrell(str) ("<span class='skrell'>" + str + "</span>")
#define span_skrellfar(str) ("<span class='skrellfar'>" + str + "</span>")
#define span_soghun(str) ("<span class='soghun'>" + str + "</span>")
#define span_solcom(str) ("<span class='solcom'>" + str + "</span>")
#define span_changeling(str) ("<span class='changeling'>" + str + "</span>")
#define span_sergal(str) ("<span class='sergal'>" + str + "</span>")
#define span_birdsongc(str) ("<span class='birdsongc'>" + str + "</span>")
#define span_vulpkanin(str) ("<span class='vulpkanin'>" + str + "</span>")
#define span_enochian(str) ("<span class='enochian'>" + str + "</span>")
#define span_daemon(str) ("<span class='daemon'>" + str + "</span>")
#define span_bug(str) ("<span class='bug'>" + str + "</span>")
#define span_vox(str) ("<span class='vox'>" + str + "</span>")
#define span_zaddat(str) ("<span class='zaddat'>" + str + "</span>")
#define span_promethean(str) ("<span class='promethean'>" + str + "</span>")
#define span_rough(str) ("<span class='rough'>" + str + "</span>")
#define span_say_quote(str) ("<span class='say_quote'>" + str + "</span>")
#define span_terminus(str) ("<span class='terminus'>" + str + "</span>")
#define span_interface(str) ("<span class='interface'>" + str + "</span>")
#define span_spacer(str) ("<span class='spacer'>" + str + "</span>")
#define span_blob(str) ("<span class='blob'>" + str + "</span>")
#define span_teppi(str) ("<span class='teppi'>" + str + "</span>")

#define span_debug_error(str) ("<span class='debug_error'>" + str + "</span>")
#define span_debug_warning(str) ("<span class='debug_warning'>" + str + "</span>")
#define span_debug_info(str) ("<span class='debug_info'>" + str + "</span>")
#define span_debug_debug(str) ("<span class='debug_debug'>" + str + "</span>")
#define span_debug_trace(str) ("<span class='debug_trace'>" + str + "</span>")

#define span_black(str) ("<span class='black'>" + str + "</span>")
#define span_darkgray(str) ("<span class='darkgray'>" + str + "</span>")
#define span_gray(str) ("<span class='gray'>" + str + "</span>")
#define span_red(str) ("<span class='red'>" + str + "</span>")
#define span_orange(str) ("<span class='orange'>" + str + "</span>")
#define span_blue(str) ("<span class='blue'>" + str + "</span>")
#define span_green(str) ("<span class='green'>" + str + "</span>")
#define span_purple(str) ("<span class='purple'>" + str + "</span>")
#define span_yellow(str) ("<span class='yellow'>" + str + "</span>")
#define span_pink(str) ("<span class='pink'>" + str + "</span>")
#define span_cyan(str) ("<span class='cyan'>" + str + "</span>")
#define span_crimson(str) ("<span class='crimson'>" + str + "</span>")
#define span_maroon(str) ("<span class='maroon'>" + str + "</span>")
#define span_brown(str) ("<span class='brown'>" + str + "</span>")
