// Default species get default sprites, VR species get VR sprites
#define VR_SPECIES_SPRITE_SHEETS_SUIT_MOB list(\
SPECIES_HUMAN = 'icons/inventory/suit/mob.dmi',\
SPECIES_TAJ = 'icons/inventory/suit/mob_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/suit/mob_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/suit/mob_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/suit/mob_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/suit/mob_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/suit/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/suit/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/suit/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/suit/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/suit/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/suit/mob_vr_vulpkanin.dmi')
#define VR_SPECIES_SPRITE_SHEETS_HEAD_MOB list(\
SPECIES_HUMAN = 'icons/inventory/head/mob.dmi',\
SPECIES_TAJ = 'icons/inventory/head/mob_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/head/mob_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/head/mob_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/head/mob_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/head/mob_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/head/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/head/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/head/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/head/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/head/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/head/mob_vr_vulpkanin.dmi')
#define VR_SPECIES_SPRITE_SHEETS_HANDS_MOB list(\
SPECIES_HUMAN = 'icons/inventory/hands/mob.dmi',\
SPECIES_TAJ = 'icons/inventory/hands/mob_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/hands/mob_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/hands/mob_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/hands/mob_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/hands/mob_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/hands/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/hands/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/hands/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/hands/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/hands/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/hands/mob_vr_vulpkanin.dmi')
#define VR_SPECIES_SPRITE_SHEETS_FEET_MOB list(\
SPECIES_HUMAN = 'icons/inventory/feet/mob.dmi',\
SPECIES_TAJ = 'icons/inventory/feet/mob_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/feet/mob_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/feet/mob_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/feet/mob_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/feet/mob_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/feet/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/feet/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/feet/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/feet/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/feet/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/feet/mob_vr_vulpkanin.dmi')

#define VR_SPECIES_SPRITE_SHEETS_SUIT_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/suit/item.dmi',\
SPECIES_TAJ = 'icons/inventory/suit/item_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/suit/item_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/suit/item_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/suit/item_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/suit/item_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/suit/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/suit/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/suit/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/suit/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/suit/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/suit/item_vr_vulpkanin.dmi')
#define VR_SPECIES_SPRITE_SHEETS_HEAD_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/head/item.dmi',\
SPECIES_TAJ = 'icons/inventory/head/item_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/head/item_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/head/item_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/head/item_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/head/item_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/head/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/head/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/head/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/head/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/head/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/head/item_vr_vulpkanin.dmi')
#define VR_SPECIES_SPRITE_SHEETS_HANDS_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/hands/item.dmi',\
SPECIES_TAJ = 'icons/inventory/hands/item_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/hands/item_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/hands/item_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/hands/item_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/hands/item_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/hands/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/hands/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/hands/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/hands/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/hands/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/hands/item_vr_vulpkanin.dmi')
#define VR_SPECIES_SPRITE_SHEETS_FEET_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/feet/item.dmi',\
SPECIES_TAJ = 'icons/inventory/feet/item_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/feet/item_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/feet/item_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/feet/item_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/feet/item_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/feet/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/feet/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/feet/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/feet/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/feet/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/feet/item_vr_vulpkanin.dmi')

// All species get VR sprites
#define ALL_VR_SPRITE_SHEETS_SUIT_MOB list(\
SPECIES_HUMAN = 'icons/inventory/suit/mob_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/suit/mob_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/suit/mob_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/suit/mob_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/suit/mob_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/suit/mob_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/suit/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/suit/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/suit/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/suit/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/suit/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/suit/mob_vr_vulpkanin.dmi')
#define ALL_VR_SPRITE_SHEETS_HEAD_MOB list(\
SPECIES_HUMAN = 'icons/inventory/head/mob_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/head/mob_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/head/mob_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/head/mob_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/head/mob_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/head/mob_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/head/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/head/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/head/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/head/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/head/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/head/mob_vr_vulpkanin.dmi')
#define ALL_VR_SPRITE_SHEETS_HANDS_MOB list(\
SPECIES_HUMAN = 'icons/inventory/hands/mob_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/hands/mob_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/hands/mob_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/hands/mob_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/hands/mob_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/hands/mob_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/hands/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/hands/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/hands/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/hands/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/hands/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/hands/mob_vr_vulpkanin.dmi')
#define ALL_VR_SPRITE_SHEETS_FEET_MOB list(\
SPECIES_HUMAN = 'icons/inventory/feet/mob_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/feet/mob_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/feet/mob_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/feet/mob_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/feet/mob_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/feet/mob_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/feet/mob_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/feet/mob_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/feet/mob_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/feet/mob_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/feet/mob_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/feet/mob_vr_vulpkanin.dmi')

#define ALL_VR_SPRITE_SHEETS_SUIT_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/suit/item_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/suit/item_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/suit/item_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/suit/item_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/suit/item_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/suit/item_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/suit/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/suit/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/suit/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/suit/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/suit/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/suit/item_vr_vulpkanin.dmi')
#define ALL_VR_SPRITE_SHEETS_HEAD_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/head/item_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/head/item_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/head/item_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/head/item_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/head/item_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/head/item_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/head/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/head/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/head/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/head/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/head/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/head/item_vr_vulpkanin.dmi')
#define ALL_VR_SPRITE_SHEETS_HANDS_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/hands/item_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/hands/item_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/hands/item_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/hands/item_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/hands/item_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/hands/item_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/hands/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/hands/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/hands/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/hands/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/hands/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/hands/item_vr_vulpkanin.dmi')
#define ALL_VR_SPRITE_SHEETS_FEET_ITEM list(\
SPECIES_HUMAN = 'icons/inventory/feet/item_vr.dmi',\
SPECIES_TAJ = 'icons/inventory/feet/item_vr_tajaran.dmi',\
SPECIES_SKRELL = 'icons/inventory/feet/item_vr_skrell.dmi',\
SPECIES_UNATHI = 'icons/inventory/feet/item_vr_unathi.dmi',\
SPECIES_TESHARI = 'icons/inventory/feet/item_vr_teshari.dmi',\
SPECIES_XENOHYBRID = 'icons/inventory/feet/item_vr_unathi.dmi',\
SPECIES_AKULA = 'icons/inventory/feet/item_vr_akula.dmi',\
SPECIES_SERGAL = 'icons/inventory/feet/item_vr_sergal.dmi',\
SPECIES_NEVREAN = 'icons/inventory/feet/item_vr_sergal.dmi',\
SPECIES_VULPKANIN = 'icons/inventory/feet/item_vr_vulpkanin.dmi',\
SPECIES_ZORREN_HIGH = 'icons/inventory/feet/item_vr_vulpkanin.dmi',\
SPECIES_FENNEC = 'icons/inventory/feet/item_vr_vulpkanin.dmi')