#define SQLITE_TABLE_FEEDBACK		"feedback"

#define SQLITE_FEEDBACK_COLUMN_ID			"id"
#define SQLITE_FEEDBACK_COLUMN_AUTHOR		"author"
#define SQLITE_FEEDBACK_COLUMN_TOPIC		"topic"
#define SQLITE_FEEDBACK_COLUMN_CONTENT		"content"
#define SQLITE_FEEDBACK_COLUMN_DATETIME		"datetime"