#define VORE_SOUND_FALLOFF 0.1
#define VORE_SOUND_RANGE 3

#define HOLO_ORIGINAL_COLOR null //Original hologram color: "#7db4e1"
#define HOLO_HARDLIGHT_COLOR "#d97de0"
#define HOLO_ORIGINAL_ALPHA 120
#define HOLO_HARDLIGHT_ALPHA 200

#define BELLIES_MAX 40
#define BELLIES_NAME_MIN 2
#define BELLIES_NAME_MAX 40
#define BELLIES_DESC_MAX 8192
#define BELLIES_EXAMINE_MAX 2048
#define BELLIES_IDLE_MAX 2048
#define BELLIES_MESSAGE_MAX 1024
#define BELLIES_MESSAGE_COMBINED 1024 * 10 + 18
#define FLAVOR_MAX 400

#define VORE_SC_MAX 2048
#define VORE_SC_DESC_MAX 8192

#define VORE_VERSION	2	//This is a Define so you don't have to worry about magic numbers.

#define VPANEL_DESCRIPTION_TAB 0
#define VPANEL_EXAMINE_TAB 1
#define VPANEL_TRASH_EATER_TAB 2
#define VPANEL_STRUGGLE_TAB 3
#define VPANEL_ESCAPE_TAB 4
#define VPANEL_ESCAPE_ABSORBED_TAB 5
#define VPANEL_TRANSFER_TAB 6
#define VPANEL_INTERACTION_TAB 7
#define VPANEL_BELLYMODE_TAB 8
#define VPANEL_IDLE_TAB 9
#define VPANEL_LIQUIDS_TAB 10

#define VORE_RESIZE_COST 125
