#define BLOB_CORE_PULSE_RANGE	6
#define BLOB_NODE_PULSE_RANGE	4

#define BLOB_CORE_EXPAND_RANGE	8
#define BLOB_NODE_EXPAND_RANGE	6

#define BLOB_DIFFICULTY_EASY		0
#define BLOB_DIFFICULTY_MEDIUM		1
#define BLOB_DIFFICULTY_HARD		2
#define BLOB_DIFFICULTY_SUPERHARD	3