// Black cards.
/obj/item/weapon/deck/cah/black/card_text_list = list(
	"Why am I itchy?",
	"Today, Security shot ____.",
	"The Chaplain this shift is worshiping _____.",
	"Cargo ordered a crate full of _____.",
	"An ERT was called due to ______.",
	"Alert! The Colony Director has armed themselves with _____.",
	"Current Laws: ________ is your master.",
	"Current Laws: ________ is the enemy.",
	"_____ vented the entirety of Cargo.",
	"Today, science found an anomaly that made people ____ and ____.",
	"There was a rap battle between ____ and ____.",
	"Caution, ______ have been detected in collision course with the station.",
	"Today's kitchen menu includes _______.",
	"What did the mercenaries want when they attacked the station?",
	"I think the Colony Director is insane. He just demanded ______ in his office.",
	"Fuckin' scientists, they just turned Misc. Research into _______ .",
	"What's my fetish?",
	"Hello, _______ here with _______",
	"No one else was at _______, they wouldn't understand the ______",
	"Why am I shivering?",
	"What is this world coming to? First, ________, now _______",
	"NanoTrasen's labor union decided to use _______ to raise employee morale.",
	"The Chemist's drug of choice is ______",
	"It is common practice for _______ to ______ on Moghes.",
	"Mercurial Colonies are _____.",
	"The Skrell are celebrating _____ today.",
	"_____ is/are why I'm afraid of the maintenance tunnels.",
	"_____ used ____ to create their newest invention, _____!",
	"Scientists are not allowed to make Gatling _____.",
	"It's not a party until the ____ arrive.",
	"No matter how many Tajaran you have, _____ is never acceptable.",
	"No, the AI's first law is NOT to serve _____.",
	"The robots are not disposal bins for your _____.",
	"You can never have too many _____ on shift.",
	)