// White cards.
/obj/item/weapon/deck/cah/var/list/card_text_list = list(
	"Those motherfucking carp",
	"Having sex in the maintenance tunnels",
	"Space 'Nam",
	"Space lesbians",
	"The Gardener getting SUPER high",
	"The Colony Director thinking they're a badass",
	"Being in a cult",
	"Racially biased lawsets",
	"An Unathi who WON'T STOP FIGHTING",
	"Tajaran fetishists",
	"Bald thirty-year-olds",
	"A Chief Engineer who can't setup the engine",
	"Being sucked out into space",
	"Officer Beepsky",
	"Engineering",
	"The grey tide.",
	"The Research Director",
	"Fucking synths",
	"Man-eating purple pod plants",
	"Chemical sprayers filled with lube",
	"Librarians",
	"Squids",
	"Cats",
	"Lizards",
	"Apes",
	"Trees",
	"Supermatter undergarments",
	"Bluespace",
	"Five hundred rabid spiders",
	"Five hundred rabid diona nymphs",
	"Cable ties",
	"Rampant vending machines",
	"Positronic drink coasters",
	"Kitchen utensil anomalies",
	"Locked lockers",
	"Energy spatulas",
	"Flashbang gauntlets",
	"Carp",
	"Space whales",
	"Blu-sharks",
	"Fax machines",
	"Exquisite Pens",
	"Dr. Maxman's male enhancements",
	"Gyrating slimes",
	"Forehead-mounted laser weaponry",
	"Pelvis-mounted laser weaponry",
	"Cardboard cutouts",
	"An obscene amount of rubber ducks",
	"Brain cakes",
	"A drone's game of life.",
	"Anomaly suits",
	"A gardener smoking reishi",
	"Military-grade baseball bats",
	"Barricading the bar",
	"An irritatingly chipper robot",
	"Androids hanging out in the bar drinking beer",
	"Gear harnesses",
	"A seventeen-year-old Colony Director",
	"The throbbing erection that the HoS gets at the thought of shooting something",
	"Trying to stab someone and hugging them instead",
	"Waking up naked in the maintenance tunnels",
	"Horrible cloning accidents",
	"Licking the supermatter due to a dare",
	"A Quartermaster who WON'T STOP ordering guns",
	"Teaching a synthetic the Birds and the Bees",
	"Unnecessary surgery",
	"My addiction to spiders",
	"wetskrell.nt",
	"DOCTOR MAXMAN!",
	"A group of Skrell getting their squish on",
	"Enough soporific to put the entire station down",
	"Delicious Vietnamese cuisine"
	)
