/obj/machinery/computer/arcade
	prizes = list(	/obj/item/storage/box/snappops							= 2,
							/obj/item/toy/blink										= 2,
							/obj/item/clothing/under/syndicate/tacticool			= 2,
							/obj/item/toy/sword										= 2,
							/obj/item/storage/box/capguntoy					= 2,
							/obj/item/gun/projectile/revolver/toy/crossbow	= 2,
							/obj/item/clothing/suit/syndicatefake					= 2,
							/obj/item/storage/fancy/crayons					= 2,
							/obj/item/toy/spinningtoy								= 2,
							/obj/random/mech_toy									= 1,
							/obj/item/reagent_containers/spray/waterflower	= 1,
							/obj/random/action_figure								= 1,
							/obj/random/plushie										= 1,
							/obj/item/toy/cultsword									= 1,
							/obj/item/toy/bouquet/fake								= 1,
							/obj/item/clothing/accessory/badge/sheriff				= 2,
							/obj/item/clothing/head/cowboy/small					= 2,
							/obj/item/toy/stickhorse								= 2,
							/obj/item/toy/rock										= 2,
							/obj/item/toy/flash										= 2,
							/obj/item/toy/redbutton									= 2,
							/obj/item/toy/gnome										= 2,
							/obj/item/toy/AI										= 2,
							/obj/item/clothing/gloves/ring/buzzer/toy				= 2,
							/obj/item/storage/box/handcuffs/fake				= 2,
							/obj/item/toy/nuke										= 2,
							/obj/item/toy/minigibber								= 2,
							/obj/item/toy/toy_xeno									= 2,
							/obj/item/toy/monster_bait						= 2,
							/obj/item/toy/russian_revolver							= 1,
							/obj/item/toy/russian_revolver/trick_revolver			= 1,
							/obj/item/toy/chainsaw									= 1,
							/obj/random/miniature									= 1,
							/obj/item/toy/snake_popper								= 1
							)