/mob/living/simple_animal/hostile/vore/large/panther
	name = "panther"
	desc = "Runtime's larger, less cuddly cousin."
	icon_state = "panther"
	icon_living = "panther"
	icon_dead = "panther-dead"
	speak = list("RAWR!","Rawr!","GRR!","Growl!")
	speak_emote = list("growls", "roars")
	emote_hear = list("rawrs","rumbles","rowls")
	emote_see = list("stares ferociously", "snarls")
	move_to_delay = 4
	maxHealth = 200
	health = 200
	melee_damage_lower = 10
	melee_damage_upper = 30
	old_y = 0
	pixel_y = 0
	capacity = 2
	faction = "panther"