/datum/lore/loremaster
	var/list/appreciation_targets = list(
										"human",
										"tajaran",
										"vulpkanin",
										"akula",
										"altevian",
										"shadekin",
										"promethean",
										"protean",
										"skrell",
										"unathi",
										"sergal",
										"synth",
										"drone",
										"cyborg",
										"AI",
										"teshari",
										"unathi",
										"vasilissan",
										"vox",
										"zaddat",
										"diona",
										"zorren",
										"goth",
										"catgirl",
										"catgirl (male)",
										"dog",
										"wolf",
										"cat",
										"mouse",
										"fox",
										"big cat",
										"bear",
										"bunny",
										"squirrel",
										"otter",
										"sheep",
										"scel",
										"fish",
										"mermaid",
										"bovine",
										"capybara",
										"reptile",
										"lizard",
										"frog",
										"snake",
										"lamia",
										"centaur",
										"minotaur",
										"wolftaur",
										"dragon",
										"amphibian",
										"wyvern",
										"food",
										"bird",
										"angel",
										"demon",
										"incubus",
										"succubus",
										"demi-human",
										"vampire",
										"plant",
										"insect",
										"arachnid",
										"monster",
										"scene girl", //Now getting into a few sillier ones
										"jock",
										"problem causer",
										"old person",
										"coworker",
										"enemy",
										"boss",
										"chav",
										"janitor",
										"friend",
										"loser",
										"politician",
										"employee",
										"somebody",
										"NanoTrasen",
										"INSERT SPECIES HERE"
	)

	var/list/appreciation_messages = list(
										"Be sure to show them your love today!",
										"Get out there and appreciate them!",
										"Wait... Is that right? Well, it's what it says. So, yeah.",
										"Maybe spend a little more time getting to know them today!",
										"Oh! I'm one of those!",
										"There's got to be some of those around here somewhere, so go appreciate them.",
										"Never met one in my life, honestly, but there you go.",
										"It's true, look it up.",
										"Maybe find the time to give them a gift or something.",
										"When's appreciation day announcer appreciation day?",
										"I will tell you, I sure do appreciate them!",
										"NanoTrasen wants it's appreciation for their general existence to be heard.",
										"I'm sure they'd appreciate a hug or something. Maybe not though, ask first.",
										"God, I wish I was one. Is that okay to say?",
										"Lots of love, NanoTrasen. Ex-Oh, Ex-Oh, Ex-Oh, mwha, mwha, mwha.",
										"Okay?",
										"Funny seeing those all the way out here, right?",
										"Great time to learn a bit about their culture!",
										"They really are, truly, very appreciated.",
										"They're just rad.",
										"They are JUST like me!"
	)

	var/list/terrible_factoids = list(
									"They are well known for their diverse modes of expression, which is said to be the cornerstone of their creative arts.",
									"They're known for their strong connection to their herritage, and their passing on of knowledge from one generation to the next.",
									"Their customs and rituals are renowned across the galaxy, and are the foundation of their society.",
									"Once tied to their homeworld(s), they are now proud spacefarers and an essential part of the greater galactic diaspora.",
									"Adaptability is said to be a fundamental strength found amongst every one of them.",
									"Known for their forward thinking mindset and interspecies empathy, they hold seats in intergalactic politics.",
									"The producers of many great technology that are proudly shared with the galactic community.",
									"NanoTrasen is proud to have strong relationships with them, intergrating them well in our many workplaces.",
									"Famous for their excellent culinary utility, they leave many an employee watering at the mouth.",
									"Kinship is a dominant trait amongst them, each of us would be lucky to hold their friendship.",
									"There are rumours that they are the direct inheritors of a precursor species.",
									"They have mastered the art of problem solving, particularly in respect to the unique challenges that they face.",
									"Unfortunately, they do not have any inherent magical ability, having to get by on their mundane skill.",
									"They have a biology not entirely unlike others that you might encounter here, whilst still retaining many distinct features that set them apart.",
									"It is said that they have evolved around an innate sense of social networking.",
									"Did you know that whilst they might seem to have a specific naming scheme, this is actually as varied as any other within their native tongue.",
									"To be honest, they're just, like, really neat.",
									"Whilst it is easy to think that you know them from their outward appearance, you should really consider getting beyond the surface, see who they are on the inside."
	)
