/datum/lore/loremaster
	var/list/appreciation_targets = list(
										"human",
										"tajaran",
										"vulpkanin",
										"akula",
										"altevian",
										"shadekin",
										"promethean",
										"protean",
										"skrell",
										"unathi",
										"synth",
										"drone",
										"cyborg",
										"AI",
										"teshari",
										"unathi",
										"vasilissan",
										"vox",
										"zaddat",
										"diona",
										"zoren",
										"goth",
										"catgirl",
										"catgirl (male)",
										"dog",
										"wolf",
										"cat",
										"mouse",
										"fox",
										"big cat",
										"bear",
										"bunny",
										"sheep",
										"scel",
										"fish",
										"mermaid",
										"bovine",
										"capybara",
										"reptile",
										"lizard",
										"snake",
										"dragon",
										"amphibian",
										"wyvern",
										"food",
										"bird",
										"angel",
										"demon",
										"incubus",
										"succubus",
										"demi-human",
										"vampire",
										"plant",
										"insect",
										"arachnid",
										"monster",
										"scene girl", //Now getting into a few sillier ones
										"jock",
										"problem causer",
										"old person",
										"coworker",
										"enemy",
										"boss",
										"chav",
										"janitor",
										"friend",
										"loser",
										"politician",
										"employee",
										"somebody",
										"NanoTrasen",
										"INSERT SPECIES HERE"
	)

	var/list/appreciation_messages = list(
										"Be sure to show them your love today!",
										"Get out there and appreciate them!",
										"Wait... Is that right? Well, it's what it says. So, yeah.",
										"Maybe spend a little more time getting to know them today!",
										"Oh! I'm one of those!",
										"There's got to be some of those around here somewhere, so go appreciate them.",
										"Never met one in my life, honestly, but there you go.",
										"It's true, look it up.",
										"Maybe find the time to give them a gift or something.",
										"When's appreciation day announcer appreciation day?",
										"I will tell you, I sure do appreciate them!",
										"NanoTrasen wants it's appreciation for their general existence to be heard.",
										"I'm sure they'd appreciate a hug or something. Maybe not though, ask first.",
										"God, I wish I was one. Is that okay to say?",
										"Lots of love, NanoTrasen. Ex-Oh, Ex-Oh, Ex-Oh, mwha, mwha, mwha.",
										"Okay?",
										"Funny seeing those all the way out here, right?",
										"Great time to learn a bit about their culture!",
										"They really are, truly, very appreciated.",
										"They're just rad."
	)
