//admin verb groups - They can overlap if you so wish. Only one of each verb will exist in the verbs list regardless
GLOBAL_LIST_INIT(admin_verbs_admin, list(
	/datum/admins/proc/show_game_mode,  //Configuration window for the current game mode.,
	/datum/admins/proc/force_mode_latespawn, //Force the mode to try a latespawn proc,
	/datum/admins/proc/force_antag_latespawn, //Force a specific template to try a latespawn proc,
	/datum/admins/proc/toggleguests,	//toggles whether guests can join the current game,
	/datum/admins/proc/announce,		//priority announce something to all clients.,
	/datum/admins/proc/intercom,		//send a fake intercom message, like an arrivals announcement,
	/datum/admins/proc/intercom_convo,	//send a fake intercom conversation, like an ATC exchange,
	/client/proc/hide_verbs,			//hides all our adminverbs,
	/client/proc/hide_most_verbs,		//hides all our hideable adminverbs,
	/client/proc/cmd_admin_subtle_message,	//send an message to somebody as a 'voice in their head',
	/client/proc/cmd_admin_check_player_logs,	//checks a player's attack logs,
	/client/proc/cmd_admin_check_dialogue_logs,	//checks a player's dialogue logs,
	/datum/admins/proc/access_news_network,	//allows access of newscasters,
	/client/proc/jumptocoord,			//we ghost and jump to a coordinate,
	/client/proc/Getmob,				//teleports a mob to our location,
	/client/proc/Getkey,				//teleports a mob with a certain ckey to our location,
	/client/proc/Jump,
	/client/proc/jumptokey,				//allows us to jump to the location of a mob with a certain ckey,
	/client/proc/jumptomob,				//allows us to jump to a specific mob,
	/client/proc/cmd_admin_direct_narrate,	//send text directly to a player with no padding. Useful for narratives and fluff-text,
	/client/proc/cmd_admin_world_narrate,	//sends text to all players with no padding,
	/client/proc/check_ai_laws,			//shows AI and borg laws,
	/client/proc/rename_silicon,		//properly renames silicons,
	/client/proc/manage_silicon_laws,	// Allows viewing and editing silicon laws. ,
	/client/proc/modify_robot,
	/client/proc/dsay,					//talk in deadchat using our ckey/fakekey,
	/datum/admins/proc/toggleooc,		//toggles ooc on/off for everyone,
	/datum/admins/proc/togglelooc,		//toggles looc on/off for everyone,
	/datum/admins/proc/toggleoocdead,	//toggles ooc on/off for everyone who is dead,
	/datum/admins/proc/togglehubvisibility, //toggles visibility on the BYOND Hub.,
	/datum/admins/proc/toggledsay,		//toggles dsay on/off for everyone,
	/client/proc/free_slot,			//frees slot for chosen job,
	/client/proc/cmd_admin_change_custom_event,
	/client/proc/toggleghostwriters,
	/client/proc/toggledrones,
	/client/proc/man_up,
	/client/proc/global_man_up,
	/client/proc/response_team, // Response Teams admin verb,
	/client/proc/trader_ship, // Trader ship admin verb,
	/client/proc/event_manager_panel,
	/client/proc/empty_ai_core_toggle_latejoin,
	/client/proc/empty_ai_core_toggle_latejoin,
	/client/proc/aooc,
	/client/proc/change_human_appearance_admin,	// Allows an admin to change the basic appearance of human-based mobs ,
	/client/proc/change_human_appearance_self,	// Allows the human-based mob itself change its basic appearance ,
	/client/proc/change_security_level,
	/client/proc/view_chemical_reaction_logs,
	/client/proc/makepAI,
	/datum/admins/proc/paralyze_mob,
	/datum/admins/proc/set_uplink,
	/datum/admins/proc/view_feedback,
	/client/proc/delbook,
	/client/proc/toggle_spawning_with_recolour,
	/client/proc/start_vote,
	/client/proc/hide_motion_tracker_feedback
	))

GLOBAL_LIST_INIT(admin_verbs_debug, list(
	/client/proc/Debug2,
	/client/proc/kill_air,
	/client/proc/ZASSettings,
	/client/proc/kill_airgroup,
	/client/proc/cmd_debug_mob_lists,
	/client/proc/cmd_debug_using_map,
	/client/proc/cmd_display_del_log,
	/client/proc/cmd_display_init_log,
	/client/proc/air_report,
	/client/proc/reload_admins,
	/client/proc/reload_eventMs,
	/client/proc/print_random_map,
	/client/proc/create_random_map,
	/client/proc/apply_random_map,
	/client/proc/overlay_random_map,
	/client/proc/delete_random_map,
	/client/proc/show_plant_genes,
	/client/proc/enable_debug_verbs,
	/client/proc/Jump,
	/client/proc/jumptomob,
	/client/proc/jumptocoord,
	/client/proc/dsay,
	/client/proc/hide_verbs,			//hides all our adminverbs,
	/client/proc/hide_most_verbs,		//hides all our hideable adminverbs,
	/datum/admins/proc/set_uplink,
	/datum/admins/proc/change_weather,
	/datum/admins/proc/change_time,
	/client/proc/cmd_regenerate_asset_cache,
	/client/proc/cmd_clear_smart_asset_cache,
	/client/proc/cmd_reload_robot_sprite_test,
	/client/proc/simple_DPS,
	/datum/admins/proc/view_feedback,
	/client/proc/stop_sounds,
	))

//verbs which can be hidden - needs work
GLOBAL_LIST_INIT(admin_verbs_hideable, list(
//	/client/proc/deadchat,
	/datum/admins/proc/toggleguests,
	/datum/admins/proc/announce,
	/client/proc/cmd_admin_subtle_message,
	/client/proc/cmd_admin_check_player_logs,
	/client/proc/cmd_admin_check_dialogue_logs,
	/datum/admins/proc/access_news_network,
	/client/proc/cmd_admin_direct_narrate,
	/client/proc/cmd_admin_world_narrate,
	/client/proc/Debug2,
	/client/proc/reload_admins,
	/client/proc/kill_air,
	/client/proc/kill_airgroup,
	/client/proc/startSinglo,
	/client/proc/simple_DPS,
	/client/proc/cmd_debug_mob_lists,
	/client/proc/cmd_debug_using_map,
	/client/proc/cmd_display_del_log,
	/client/proc/air_report,
	/client/proc/enable_debug_verbs,
	/datum/admins/proc/set_uplink,
	/client/proc/stop_sounds
	))

GLOBAL_LIST_INIT(admin_verbs_mod, list(
	/client/proc/hide_verbs,			//hides all our adminverbs,
	/client/proc/hide_most_verbs,		//hides all our hideable adminverbs,
	/client/proc/dsay,
	/client/proc/aooc,
	/client/proc/cmd_admin_subtle_message, 	//send an message to somebody as a 'voice in their head',
	/datum/admins/proc/paralyze_mob,
	/client/proc/cmd_admin_direct_narrate,
	/datum/admins/proc/view_persistent_data,
	/client/proc/start_vote
))

GLOBAL_LIST_INIT(admin_verbs_event_manager, list(
	/client/proc/hide_verbs,			//hides all our adminverbs,
	/client/proc/hide_most_verbs,		//hides all our hideable adminverbs,
	/client/proc/dsay,
	/client/proc/cmd_admin_subtle_message,
	/client/proc/aooc,
	/datum/admins/proc/paralyze_mob,
	/client/proc/cmd_admin_direct_narrate,
	/datum/admins/proc/change_weather,
	/datum/admins/proc/change_time,
	/client/proc/cmd_regenerate_asset_cache,
	/client/proc/cmd_clear_smart_asset_cache,
	/client/proc/cmd_reload_robot_sprite_test,
	/client/proc/Jump,
	/client/proc/jumptomob,
	/client/proc/jumptocoord,
	/datum/admins/proc/change_weather,
	/datum/admins/proc/change_time,
	/client/proc/cmd_regenerate_asset_cache,
	/client/proc/cmd_clear_smart_asset_cache,
	/client/proc/cmd_reload_robot_sprite_test,
	/datum/admins/proc/show_game_mode,  //Configuration window for the current game mode.,
	/datum/admins/proc/force_mode_latespawn, //Force the mode to try a latespawn proc,
	/datum/admins/proc/force_antag_latespawn, //Force a specific template to try a latespawn proc,
	/datum/admins/proc/announce,            //priority announce something to all clients.,
	/datum/admins/proc/intercom,            //send a fake intercom message, like an arrivals announcement,
	/datum/admins/proc/intercom_convo,      //send a fake intercom conversation, like an ATC exchange,
	/client/proc/cmd_admin_subtle_message,  //send an message to somebody as a 'voice in their head',
	/client/proc/cmd_admin_check_player_logs,       //checks a player's attack logs,
	/client/proc/cmd_admin_check_dialogue_logs,     //checks a player's dialogue logs,
	/datum/admins/proc/access_news_network, //allows access of newscasters,
	/client/proc/jumptocoord,                       //we ghost and jump to a coordinate,
	/client/proc/Getmob,                            //teleports a mob to our location,
	/client/proc/Getkey,                            //teleports a mob with a certain ckey to our location,
	/client/proc/Jump,
	/client/proc/jumptokey,                         //allows us to jump to the location of a mob with a certain ckey,
	/client/proc/jumptomob,                         //allows us to jump to a specific mob,
	/client/proc/cmd_admin_direct_narrate,  //send text directly to a player with no padding. Useful for narratives and fluff-text,
	/client/proc/cmd_admin_world_narrate,   //sends text to all players with no padding,
	/client/proc/check_ai_laws,                     //shows AI and borg laws,
	/client/proc/rename_silicon,            //properly renames silicons,
	/client/proc/manage_silicon_laws,       // Allows viewing and editing silicon laws. ,
	/client/proc/modify_robot,
	/client/proc/dsay,                                      //talk in deadchat using our ckey/fakekey,
	/client/proc/free_slot,                 //frees slot for chosen job,
	/client/proc/cmd_admin_change_custom_event,
	/client/proc/toggleghostwriters,
	/client/proc/man_up,
	/client/proc/global_man_up,
	/client/proc/response_team, // Response Teams admin verb,
	/client/proc/trader_ship, // Trader ship admin verb,
	/client/proc/event_manager_panel,
	/client/proc/aooc,
	/client/proc/change_human_appearance_admin,     // Allows an admin to change the basic appearance of human-based mobs ,
	/client/proc/change_human_appearance_self,      // Allows the human-based mob itself change its basic appearance ,
	/client/proc/change_security_level,
	/client/proc/makepAI,
	/datum/admins/proc/paralyze_mob,
	/datum/admins/proc/view_feedback,
	/client/proc/toggle_spawning_with_recolour,
	/client/proc/start_vote,
	/client/proc/add_hidden_area,
	/client/proc/remove_hidden_area,
	/client/proc/hide_motion_tracker_feedback,
	/client/proc/modify_event_collector,
	/client/proc/induce_malfunction
))
