name: Update TGS DMAPI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-dmapi:
    runs-on: ubuntu-24.04
    name: Update the TGS DMAPI
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone
        uses: actions/checkout@v5

      - name: Branch
        run: |
          git branch -f tgs-dmapi-update
          git checkout tgs-dmapi-update
          git reset --hard master

      - name: Apply DMAPI update
        uses: tgstation/tgs-dmapi-updater@v2
        id: dmapi-update
        with:
          header-path: "code/__defines/tgs.dm"
          library-path: "code/modules/tgs"

      - name: Commit and Push
        continue-on-error: true
        run: |
          git config user.name "vorestation-ci[bot]"
          git config user.email "199609141+vorestation-ci[bot]@users.noreply.github.com"
          git add .
          git commit -m 'Update TGS DMAPI'
          git push -f -u origin tgs-dmapi-update

      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v2
        if: env.APP_PRIVATE_KEY != '' && env.APP_ID != ''
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_ID: ${{ secrets.APP_ID }}

      # Create PR if changes were made
      - name: Check for changes
        run: |
          git fetch origin
          if git diff --quiet origin/master...tgs-dmapi-update; then
            echo "No changes to PR. Skipping creation."
            exit 0
          fi
      - name: Create Pull Request
        if: ${{ success() }}
        run: |
          gh pr create \
            --base master \
            --head tgs-dmapi-update \
            --title "Automatic TGS DMAPI Update" \
            --body "This pull request updates the TGS DMAPI to the latest version. Please note any changes that may be breaking or unimplemented in your codebase by checking what changes are in the definitions file: code/__DEFINES/tgs.dm before merging.\n\n${{ steps.dmapi-update.outputs.release-notes }}" \
            --label "Tools"
        env:
          GITHUB_TOKEN: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
